<a href="https://colab.research.google.com/github/VintaBytes/Ciencia-de-datos/blob/main/cursos/machine-learning-python2/Clase04/Preparaci%C3%B3n_de_datos_para_Machine_Learning_exploraci%C3%B3n_y_limpieza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab"/></a>

# Cuaderno 2 - Preparación de datos para Machine Learning: exploración y limpieza

En este cuaderno vamos a trabajar con un dataset que contiene información sobre empleados de una organización.

Cada fila representa un empleado y las columnas reúnen diferentes características, como su edad, departamento, región, fecha de ingreso, salario, estado laboral, evaluación de desempeño y modalidad de trabajo, entre otras.

El archivo que utilizaremos se llama:

`Messy_Employee_dataset_2.csv`

El dataset original fue **modificado deliberadamente con fines educativos** para incorporar algunos de los problemas que podemos encontrar al trabajar con datos reales. Entre ellos existen valores ausentes, registros duplicados, valores extremos, inconsistencias en variables categóricas, errores de escritura y diferentes formas de representar algunos datos.

No conocemos de antemano dónde se encuentran todos esos problemas.

Una parte importante del trabajo consistirá precisamente en **explorar el dataset, detectar posibles anomalías y decidir cómo tratarlas**.

Esta etapa es fundamental en un proyecto de Machine Learning. Antes de entrenar un modelo necesitamos comprender los datos con los que vamos a trabajar y asegurarnos de que tengan una estructura y una calidad adecuadas.

A lo largo del cuaderno recorreremos progresivamente tareas como:

* cargar un dataset desde un archivo CSV;
* conocer sus dimensiones, columnas y tipos de datos;
* inspeccionar las primeras observaciones;
* obtener estadísticas descriptivas;
* identificar valores ausentes;
* detectar registros duplicados;
* explorar variables numéricas y categóricas;
* encontrar valores atípicos o imposibles;
* detectar inconsistencias y errores de formato;
* corregir o transformar los datos cuando sea necesario;
* verificar finalmente el resultado de la limpieza.

La pregunta que guiará nuestro trabajo será:

> **¿Cómo podemos determinar si un dataset está realmente preparado para ser utilizado en un proyecto de Machine Learning?**

En este cuaderno todavía **no entrenaremos ningún modelo**. Nuestro objetivo será llegar al punto inmediatamente anterior: obtener un conjunto de datos comprendido, revisado y preparado para continuar posteriormente con las etapas de Machine Learning.


## Carga del dataset

Antes de comenzar a analizar los datos necesitamos incorporar el archivo CSV al entorno de trabajo de Google Colab.

En este caso utilizaremos el archivo:

`Messy_Employee_dataset_2.csv`

Primero debemos subirlo al almacenamiento temporal de la sesión de Colab. Para hacerlo podemos utilizar el panel **Archivos** ubicado en el lateral izquierdo de la interfaz y seleccionar la opción para cargar archivos.

Una vez que el archivo se encuentre disponible en el entorno, podremos leerlo con **Pandas**.

Pandas es una de las bibliotecas más utilizadas en Python para trabajar con datos tabulares. Su estructura principal es el **DataFrame**, que podemos imaginar como una tabla formada por filas y columnas.

Cada fila suele representar una observación o registro, mientras que cada columna representa una característica o variable.

En nuestro dataset:

* cada fila representa un empleado;
* cada columna contiene alguna característica asociada a ese empleado.

Al cargar el archivo no realizaremos todavía ninguna limpieza ni transformación. Es importante observar primero los datos tal como fueron recibidos, ya que parte del trabajo consistirá precisamente en detectar sus problemas.


In [ ]:
import pandas as pd

df = pd.read_csv("Messy_Employee_dataset_2.csv")

df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,TRUE
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,TRUE
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,TRUE
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,TRUE
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,FALSE


## Primera inspección del dataset

La función `head()` nos permite observar, por defecto, las primeras cinco filas del DataFrame.

Esta primera vista no alcanza para conocer completamente el dataset, pero ya nos permite reconocer su estructura general y formular algunas preguntas que después investigaremos con más detalle.

Podemos observar que cada fila parece representar a un empleado y que aparecen variables de distintos tipos:

* identificadores, como `Employee_ID`;
* datos personales, como `First_Name` y `Last_Name`;
* variables numéricas, como `Age` y `Salary`;
* variables categóricas, como `Status` y `Performance_Score`;
* información compuesta, como `Department_Region`;
* una fecha, almacenada en `Join_Date`;
* datos de contacto, como `Email` y `Phone`;
* una variable binaria, `Remote_Work`.

También aparecen ya algunos detalles que llaman la atención.

Por ejemplo, en las primeras cinco filas hay valores ausentes en `Age`, representados como `NaN`.

Además, la columna `Phone` contiene valores negativos. Aunque Pandas pueda interpretar esos valores como números, debemos recordar que **un número de teléfono no representa una cantidad sobre la cual tenga sentido realizar operaciones aritméticas**. Más adelante tendremos que analizar cómo conviene tratar esta columna.

La columna `Join_Date` muestra fechas con una estructura como:

```text
4/2/2021
7/10/2020
12/7/2023
```

A simple vista parecen fechas válidas, pero todavía no sabemos cómo las interpretó Pandas ni si todo el dataset utiliza el mismo formato.

Finalmente, `Remote_Work` aparece representado mediante valores como `TRUE` y `FALSE`. También tendremos que comprobar qué tipo de dato asignó Pandas a esta columna.

Esta primera observación nos muestra una idea importante:

> **Mirar las primeras filas nos permite familiarizarnos con los datos, pero no es suficiente para conocer su estructura ni detectar todos sus problemas.**

El siguiente paso será averiguar **cuántas filas y columnas tiene el dataset**.


In [ ]:
df.shape

(1048, 12)

## Dimensiones del dataset

El atributo `shape` nos informa las dimensiones del DataFrame mediante una tupla con la forma:

```text
(filas, columnas)
```

En nuestro caso obtuvimos:

```text
(1048, 12)
```

Esto significa que el dataset contiene:

* **1048 filas**
* **12 columnas**

Por el momento, esta información solamente nos permite conocer el tamaño de la tabla.

Todavía no sabemos, por ejemplo:

* qué tipo de dato tiene cada columna;
* cuántos valores faltantes existen;
* si hay columnas con tipos inadecuados;
* si aparecen duplicados;
* si existen valores atípicos o inconsistentes.

Para avanzar con esa inspección, el siguiente paso será obtener un resumen general de la estructura del DataFrame.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Employee_ID        1048 non-null   object 
 1   First_Name         1048 non-null   object 
 2   Last_Name          1048 non-null   object 
 3   Age                831 non-null    float64
 4   Department_Region  1039 non-null   object 
 5   Status             1039 non-null   object 
 6   Join_Date          1042 non-null   object 
 7   Salary             1024 non-null   float64
 8   Email              1042 non-null   object 
 9   Phone              1048 non-null   int64  
 10  Performance_Score  1039 non-null   object 
 11  Remote_Work        1042 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 98.4+ KB


## Estructura general y tipos de datos

La función `info()` nos ofrece una visión general del DataFrame.

En la salida podemos confirmar que tenemos **1048 registros** y **12 columnas**. También podemos ver, para cada columna:

* cuántos valores no nulos contiene;
* qué tipo de dato (`dtype`) asignó Pandas.

En este caso aparecen tres tipos de datos principales:

```text
float64
int64
object
```

Las columnas `Age` y `Salary` fueron interpretadas como `float64`, mientras que `Phone` fue interpretada como `int64`.

Las demás columnas fueron interpretadas como `object`, incluyendo algunas que, por su contenido, quizá más adelante necesiten una revisión más detallada, como `Join_Date` o `Remote_Work`.

La salida también permite detectar que varias columnas tienen menos de 1048 valores no nulos.

Por ejemplo:

* `Age` tiene 831 valores no nulos;
* `Department_Region` tiene 1039;
* `Status` tiene 1039;
* `Join_Date` tiene 1042;
* `Salary` tiene 1024;
* `Email` tiene 1042;
* `Performance_Score` tiene 1039;
* `Remote_Work` tiene 1042.

Esto nos indica que existen valores ausentes en varias columnas.

Sin embargo, `info()` nos muestra solamente cuántos valores no nulos hay. Para analizar con más claridad cuántos valores faltan en cada columna, conviene contarlos directamente.


In [ ]:
df.isna().sum()

,0
Employee_ID,0
First_Name,0
Last_Name,0
Age,217
Department_Region,9
Status,9
Join_Date,6
Salary,24
Email,6
Phone,0


## Valores ausentes

El método:

```python
df.isna().sum()
```

cuenta cuántos valores ausentes (`NaN`) existen en cada columna del DataFrame.

La salida muestra que los valores faltantes no están distribuidos de manera uniforme.

Encontramos:

* `Age`: **217** valores ausentes;
* `Department_Region`: **9**;
* `Status`: **9**;
* `Join_Date`: **6**;
* `Salary`: **24**;
* `Email`: **6**;
* `Performance_Score`: **9**;
* `Remote_Work`: **6**.

En cambio, las columnas:

* `Employee_ID`;
* `First_Name`;
* `Last_Name`;
* `Phone`;

no presentan valores ausentes.

Por ahora solamente hemos **detectado y contado** los valores faltantes. Todavía no vamos a eliminarlos ni reemplazarlos.

Esta distinción es importante: durante la exploración buscamos conocer los problemas del dataset antes de tomar decisiones sobre cómo resolverlos.

Más adelante tendremos que analizar cada caso y decidir si corresponde, por ejemplo, eliminar registros, reemplazar valores o aplicar alguna otra estrategia.

Antes de comenzar con esas decisiones conviene continuar auditando el dataset y comprobar si existen **filas duplicadas**.


## Búsqueda de registros duplicados

Otro problema frecuente en un conjunto de datos es la presencia de **registros duplicados**.

Un registro duplicado es una fila cuyos valores coinciden con los de otra fila del DataFrame. Su presencia puede alterar algunos análisis y, posteriormente, influir en los modelos construidos a partir de esos datos.

Pandas proporciona el método:

```python
df.duplicated()
```

Este método compara las filas del DataFrame y devuelve para cada una un valor booleano:

* `False` si la fila no fue identificada como duplicada;
* `True` si la fila repite una observación que apareció anteriormente.

Como los valores booleanos pueden tratarse como `0` (`False`) y `1` (`True`), podemos utilizar:

```python
df.duplicated().sum()
```

para contar directamente cuántas filas fueron identificadas como duplicadas.

Por el momento no eliminaremos ninguna. Primero queremos saber **si existen y cuántas son**.


In [ ]:
df.duplicated().sum()

np.int64(20)

## Duplicados detectados

La expresión:

```python
df.duplicated().sum()
```

devolvió:

```text
20
```

Esto significa que Pandas identificó **20 filas duplicadas completas**.

Es decir, existen 20 registros cuyos valores coinciden con los de alguna fila anterior del DataFrame.

Por ahora no sabemos todavía cuáles son esas filas ni dónde aparecen. Tampoco vamos a eliminarlas aún.

Antes de modificar el dataset conviene observar esos registros y verificar qué está detectando Pandas como duplicado.


### Opciones del parámetro `keep`

El método `duplicated()` permite indicar qué ocurrencia de un registro repetido debe tomarse como referencia mediante el parámetro `keep`.

Las opciones principales son:

```python
keep="first"
```

Conserva la primera aparición como referencia y marca como duplicadas las siguientes. Es el comportamiento por defecto.

```python
keep="last"
```

Conserva la última aparición como referencia y marca como duplicadas las anteriores.

```python
keep=False
```

Marca como duplicadas **todas** las filas que pertenecen a un grupo repetido, incluida la primera aparición.

Para inspeccionar los registros duplicados utilizaremos `keep=False`, ya que queremos ver todas las filas involucradas.


In [ ]:
df[df.duplicated(keep=False)]

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
92,EMP1092,Alice,Johnson,40.0,HR-New York,Inactive,3/10/2021,74837.75,alice.johnson@example.com,-5641118241,Poor,FALSE
94,EMP1094,David,Miller,40.0,Finance-Illinois,Active,11/15/2023,83326.52,david.miller@example.com,-2004615264,Average,TRUE
109,EMP1109,Eva,Davis,NaN,DevOps-New York,Inactive,8/23/2020,88119.37,eva.davis@example.com,-4793036148,Good,TRUE
149,EMP1149,Frank,Garcia,35.0,Sales-Florida,Pending,1/30/2022,57584.23,frank.garcia@example.com,-5669078262,Average,TRUE
184,EMP1184,Frank,Smith,25.0,Finance-Nevada,Active,6/12/2022,51311.91,frank.smith@example.com,-864035532,Excellent,FALSE
214,EMP1214,Grace,Williams,25.0,HR-New York,Active,10/14/2021,115157.81,grace.williams@example.com,-7178333210,Good,FALSE
299,EMP1299,Alice,Garcia,NaN,Sales - Nevada,Inactive,1/21/2024,51523.93,alice.garcia@example.com,-18418619,Average,TRUE
312,EMP1312,Alice,Brown,35.0,DevOps-Nevada,Inactive,5/28/2024,86712.41,alice.brown@example.com,-6501917919,Average,TRUE
449,EMP1449,Alice,Miller,30.0,Sales-Florida,NaN,9/14/2024,119407.93,alice.miller@example.com,-8469081973,Excellent,TRUE
455,EMP1455,Charlie,Williams,25.0,Sales-California,Active,2/4/2022,99317.66,charlie.williams@example.com,-662668216,Poor,FALSE


## Inspección de los registros duplicados

Al utilizar:

```python
df[df.duplicated(keep=False)]
```

Pandas mostró tanto las primeras apariciones como las copias de los registros duplicados.

Podemos observar, por ejemplo, que el empleado:

```text
EMP1109
```

aparece en las filas `109` y `1020` con exactamente los mismos valores.

Lo mismo ocurre con otros registros mostrados en la salida. Las filas ubicadas entre los índices `1020` y `1039` repiten registros que ya habían aparecido anteriormente en el DataFrame.

Esto explica el resultado obtenido previamente:

```text
20
```

Había **20 filas que eran copias completas de registros anteriores**.

Como en estos casos toda la información de la fila está repetida, mantener ambas copias no aporta información adicional. Podemos eliminar esas repeticiones conservando una sola aparición de cada registro.

Pandas proporciona para ello el método:

```python
drop_duplicates()
```

Por defecto, este método conserva la primera aparición y elimina las repeticiones posteriores.


In [ ]:
df = df.drop_duplicates()

df.shape

(1028, 12)

## Resultado

Después de aplicar:

```python
df = df.drop_duplicates()
```

el DataFrame pasó de:

```text
1048 filas
```

a:

```text
1028 filas
```

Las **12 columnas se mantuvieron sin cambios**.

Esto confirma que fueron eliminadas **20 filas duplicadas completas**.

---

## ¿Puede repetirse el identificador de un empleado?

Eliminar filas duplicadas completas no garantiza que todos los registros sean únicos desde el punto de vista lógico.

Por ejemplo, dos filas pueden contener datos diferentes y, aun así, compartir el mismo identificador.

La columna `Employee_ID` parece cumplir la función de identificar a cada empleado. Por eso conviene comprobar si alguno de sus valores aparece más de una vez.

Para hacerlo podemos utilizar:

```python
df["Employee_ID"].duplicated().sum()
```

En este caso, `duplicated()` ya no compara filas completas: analiza solamente los valores de la columna `Employee_ID`.


In [ ]:
df["Employee_ID"].duplicated().sum()

np.int64(8)

Esto significa que existen **8 valores de `Employee_ID` que aparecen nuevamente después de una primera aparición**.

Es importante notar que estos casos no fueron eliminados por `drop_duplicates()`. Por lo tanto, las filas involucradas no son copias completas entre sí: comparten el mismo identificador, pero al menos algún otro dato es diferente.

Antes de decidir qué hacer con estos registros, necesitamos verlos.


In [ ]:
df[df["Employee_ID"].duplicated(keep=False)].sort_values("Employee_ID")

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
238,EMP1238,Heidi,Williams,30.0,Sales-California,Pending,10/2/2022,64012.48,heidi.williams@example.com,-8260340847,Poor,TRUE
1042,EMP1238,Heidi,Williams,30.0,Sales-California,Pending,10/2/2022,65932.85,heidi.williams@example.com,-8260340847,Poor,TRUE
262,EMP1262,Heidi,Jones,NaN,HR-Illinois,Pending,6/5/2023,58316.77,heidi.jones@example.com,-8826170242,Excellent,TRUE
1046,EMP1262,Heidi,Jones,NaN,HR-Illinois,Pending,6/5/2023,60066.27,heidi.jones@example.com,-8826170242,Excellent,TRUE
367,EMP1367,David,Johnson,NaN,Admin-Illinois,Active,11/8/2021,89189.43,david.johnson@example.com,-882351304,Poor,TRUE
1043,EMP1367,David,Johnson,NaN,Admin-Illinois,Pending,11/8/2021,89189.43,david.johnson@example.com,-882351304,Poor,TRUE
428,EMP1428,David,Smith,NaN,Admin-Florida,Inactive,5/2/2020,118079.15,david.smith@example.com,-3170876013,Good,TRUE
1040,EMP1428,David,Smith,NaN,Admin-Florida,Inactive,5/2/2020,121621.52,david.smith@example.com,-3170876013,Good,TRUE
591,EMP1591,Bob,Garcia,30.0,DevOps-Illinois,Inactive,11/8/2021,74999.69,bob.garcia@example.com,-155029167,Good,TRUE
1047,EMP1591,Bob,Garcia,30.0,DevOps-Illinois,Pending,11/8/2021,74999.69,bob.garcia@example.com,-155029167,Good,TRUE


La búsqueda mostró **16 filas**, correspondientes a **8 identificadores de empleado repetidos**.

A diferencia de los duplicados completos que encontramos anteriormente, en estos casos las dos filas asociadas a un mismo `Employee_ID` **no son idénticas**.

Al compararlas podemos observar dos situaciones diferentes.

En algunos empleados cambia el valor de `Salary`. Por ejemplo, para `EMP1238` aparecen:

```text
64012.48
65932.85
```

mientras que el resto de los datos mostrados para ese empleado coincide.

En otros casos cambia `Status`. Por ejemplo, `EMP1367` aparece una vez como:

```text
Active
```

y otra como:

```text
Pending
```

La misma clase de diferencia aparece en otros identificadores repetidos.

Esto nos presenta un problema distinto al de los duplicados exactos:

> **sabemos que existen registros contradictorios, pero el propio dataset no nos permite determinar cuál de los dos valores es el correcto.**

No sería apropiado elegir automáticamente la primera o la última fila solamente por su posición en el archivo.

En un proyecto real, este tipo de situación debería resolverse consultando una fuente de información confiable, estableciendo una regla de negocio o verificando el origen de los registros.

En nuestro caso no contamos con información externa que permita decidir cuál de las dos versiones es correcta. Por lo tanto, debemos adoptar una estrategia explícita **y documentarla**.


### Tratamiento de los identificadores conflictivos

Como no podemos determinar cuál de las dos versiones de cada empleado es correcta, optaremos por eliminar del análisis **todas las filas correspondientes a identificadores repetidos**.

Esta decisión implica perder algunos registros, pero evita conservar información cuya validez no podemos establecer.

Primero identificaremos los `Employee_ID` que aparecen más de una vez y luego eliminaremos todas las filas asociadas a ellos.

### ¿Cómo eliminaremos los identificadores repetidos?

Para eliminar correctamente estos registros necesitamos realizar tres pasos.

Primero utilizaremos:

```python
df["Employee_ID"].duplicated(keep=False)
```

Con `keep=False`, Pandas marca como repetidas **todas las apariciones** de cada `Employee_ID` duplicado, no solamente la segunda.

Luego emplearemos:

```python
isin()
```

Este método permite comprobar si cada valor de `Employee_ID` pertenece al conjunto de identificadores repetidos.

Finalmente utilizaremos el operador:

```python
~
```

que representa una negación lógica.

De esta manera podemos conservar solamente las filas cuyo `Employee_ID` **no** pertenece al conjunto de identificadores conflictivos.

En resumen:

* `duplicated(keep=False)` localiza todas las apariciones conflictivas;
* `isin()` comprueba si cada ID pertenece a ese conjunto;
* `~` niega la condición, por lo que conservamos los registros cuyos IDs **no** están entre los repetidos.


In [ ]:
ids_repetidos = df.loc[
    df["Employee_ID"].duplicated(keep=False),
    "Employee_ID"
]

df = df[~df["Employee_ID"].isin(ids_repetidos)]

df.shape

(1012, 12)

El DataFrame quedó con:

```text
1012 filas
12 columnas
```

Antes de esta operación tenía 1028 filas.

Por lo tanto, se eliminaron **16 registros**, correspondientes a las dos apariciones de cada uno de los 8 identificadores conflictivos detectados.

Las 12 columnas se mantuvieron sin cambios.

A partir de este punto continuaremos trabajando únicamente con registros cuyo `Employee_ID` aparece una sola vez.


---

## Primera descripción de las variables numéricas

Hasta ahora analizamos la estructura general del DataFrame, los valores ausentes y los registros duplicados. El siguiente paso consiste en observar cómo se distribuyen las variables numéricas.

Pandas proporciona el método:

```python
df.describe()
```

que genera automáticamente un resumen estadístico de las columnas numéricas del DataFrame. Entre otras medidas, muestra:

* `count`: cantidad de valores no nulos;
* `mean`: media aritmética;
* `std`: desvío estándar;
* `min`: valor mínimo;
* `25%`: primer cuartil;
* `50%`: mediana;
* `75%`: tercer cuartil;
* `max`: valor máximo.

Estas medidas pueden ayudarnos a detectar valores inusuales, extremos o directamente imposibles. Por ahora no corregiremos nada. Solamente observaremos qué información nos proporciona el resumen.


In [ ]:
df.describe()

,Age,Salary,Phone
count,806.000000,9.880000e+02,1.012000e+03
mean,33.941687,9.114649e+04,-4.943883e+09
std,35.111398,1.052135e+05,2.812652e+09
min,-8.000000,-4.500000e+04,-9.994973e+09
25%,25.000000,6.825495e+04,-7.327365e+09
50%,30.000000,8.562185e+04,-4.952466e+09
75%,40.000000,1.012454e+05,-2.520391e+09
max,999.000000,2.500000e+06,-3.896086e+06


El resultado de `describe()` muestra información para tres columnas numéricas:

* `Age`
* `Salary`
* `Phone`

La columna `Age` presenta:

```text
mínimo = -8
máximo = 999
```

Estos valores resultan claramente incompatibles con una edad humana razonable, por lo que constituyen candidatos evidentes a errores. Además, la media es aproximadamente:

```text
33.94
```

pero el desvío estándar es superior a `35`, un valor llamativamente grande en relación con los cuartiles observados:

```text
25% = 25
50% = 30
75% = 40
```

Esto sugiere que algunos valores extremos están afectando fuertemente el resumen de la variable.

En `Salary` también aparecen valores que merecen revisión:

```text
mínimo = -45000
máximo = 2500000
```

Un salario negativo resulta sospechoso y un valor de 2.500.000 se encuentra muy alejado de los cuartiles:

```text
25% = 68254.95
50% = 85621.85
75% = 101245.40
```

Esto no significa automáticamente que todo valor alto sea incorrecto, pero sí indica que existen valores extremos que deberemos inspeccionar con más detalle.

La columna `Phone`, por su parte, aparece como numérica porque Pandas la interpretó como `int64`. Sin embargo, los valores observados son todos negativos y de gran magnitud.

Esto refuerza una idea importante:

> **Que Pandas asigne un tipo numérico a una columna no significa necesariamente que esa variable deba analizarse como una magnitud numérica.**

Un número de teléfono funciona como identificador o dato de contacto, no como cantidad sobre la que tenga sentido calcular una media, un desvío estándar o cuartiles.

Por lo tanto, antes de comenzar a corregir datos, conviene inspeccionar con mayor detalle las variables `Age` y `Salary`, donde el resumen estadístico ya mostró valores potencialmente problemáticos.


In [ ]:
sorted(df["Age"].dropna().unique())

[np.float64(-8.0),
 np.float64(0.0),
 np.float64(4.0),
 np.float64(15.0),
 np.float64(25.0),
 np.float64(30.0),
 np.float64(35.0),
 np.float64(40.0),
 np.float64(115.0),
 np.float64(132.0),
 np.float64(150.0),
 np.float64(999.0)]

Al obtener los valores únicos ordenados de la columna `Age`, encontramos:

```text
-8, 0, 4, 15, 25, 30, 35, 40, 115, 132, 150, 999
```

Podemos observar que aparecen edades como:

```text
25, 30, 35 y 40
```

junto con otros valores que resultan claramente incompatibles con una edad laboral razonable, por ejemplo:

```text
-8, 0, 4, 115, 132, 150 y 999
```

El valor:

```text
15
```

también merece revisión, aunque aquí conviene distinguir entre dos ideas:

> un valor poco frecuente o extremo no siempre es automáticamente un error.

En un caso real, antes de modificarlo deberíamos conocer las reglas del problema o consultar la fuente de los datos. Antes de tomar una decisión sobre la limpieza de esta columna, necesitamos saber **cuántas veces aparece cada valor**.



In [ ]:
df["Age"].value_counts(dropna=False).sort_index()

,count
Age,
-8.0,1
0.0,1
4.0,1
15.0,1
25.0,203
30.0,200
35.0,185
40.0,210
115.0,1


La tabla de frecuencias muestra cuántas veces aparece cada valor de la columna `Age`. Los resultados indican que:

```text
25 años → 203 registros
30 años → 200 registros
35 años → 185 registros
40 años → 210 registros
```

En conjunto, estos cuatro valores representan la gran mayoría de las edades registradas. En cambio, los valores:

```text
-8, 0, 4, 15, 115, 132, 150 y 999
```

aparecen **una sola vez cada uno**. También observamos:

```text
206 valores ausentes
```

representados como `NaN`. Esta distribución refuerza la sospecha de que los valores extremos son anomalías introducidas en la columna.

Para continuar con la limpieza, podemos establecer una regla sencilla para este conjunto de datos: considerar válidas solamente las edades comprendidas entre 18 y 100 años. Los valores que queden fuera de ese intervalo serán tratados como datos inválidos.

En lugar de eliminar directamente las filas, reemplazaremos esos valores por `NaN`. De esta manera, unificaremos los casos de edad desconocida o inválida y podremos decidir posteriormente cómo tratar todos los valores faltantes de forma conjunta.


In [ ]:
df.loc[(df["Age"] < 18) | (df["Age"] > 100), "Age"] = pd.NA

df["Age"].value_counts(dropna=False).sort_index()

,count
Age,
25.0,203
30.0,200
35.0,185
40.0,210
NaN,214


## Resultado de la limpieza de `Age`

Después de reemplazar por `NaN` las edades menores de 18 años o mayores de 100, la columna quedó con los siguientes valores:

```text
25 años → 203 registros
30 años → 200 registros
35 años → 185 registros
40 años → 210 registros
NaN     → 214 registros
```

Antes de la limpieza había **206 valores ausentes** en `Age`. Ahora hay:

```text
214 valores ausentes
```

La diferencia es de **8 registros**, que coincide con los ocho valores que habíamos identificado fuera del intervalo considerado válido:

```text
-8, 0, 4, 15, 115, 132, 150 y 999
```

De esta manera, los valores imposibles o no aceptados por la regla definida quedaron unificados con los valores faltantes.

Todavía no hemos decidido cómo tratar esos `NaN`. Por ahora simplemente logramos que la columna no contenga edades que contradigan el criterio de validez que establecimos.


## Inspección de los valores extremos de `Salary`

Antes de decidir que valores pueden considerarse anómalos, conviene observar directamente algunos de los salarios más pequeños y más grandes. Para hacerlo utilizaremos el método:

```python
sort_values()
```

que ordena los valores de una columna. Por defecto, el orden es ascendente:

```python
df["Salary"].sort_values()
```

por lo que los valores más pequeños aparecen primero. Si indicamos:

```python
ascending=False
```

el orden se invierte y los valores más grandes aparecen primero.

Finalmente, `head(10)` nos permite mostrar solamente los primeros 10 valores de cada resultado.

De esta manera podremos inspeccionar ambos extremos de la distribución sin tener que visualizar toda la columna.


In [ ]:
print("Salarios más bajos:")
print(df["Salary"].sort_values().head(10))

print("\nSalarios más altos:")
print(df["Salary"].sort_values(ascending=False).head(10))

Salarios más bajos:
715   -45000.00
573       -1.00
735        0.00
808      175.00
988     1200.00
394    50047.32
858    50060.73
782    50110.66
549    50153.79
390    50173.12
Name: Salary, dtype: float64

Salarios más altos:
374    2500000.00
240    1800000.00
91      999999.00
288     950000.00
578     500000.00
243     119971.65
712     119890.35
439     119801.30
96      119764.20
444     119586.11
Name: Salary, dtype: float64


Al observar los salarios más bajos encontramos que los cinco primeros valores se encuentran muy separados de los siguientes. Además, aparecen salarios negativos y un salario igual a cero, por lo que estos registros requieren una revisión especial.

En el extremo superior ocurre algo similar. Nuevamente podemos observar una separación considerable: después de `500000` el siguiente valor mostrado es aproximadamente `120000`.

Esta inspección nos permite detectar **valores sospechosos**, pero todavía no establece por sí sola cuáles deben considerarse outliers ni cuáles son necesariamente errores.

Para analizarlo con un criterio estadístico podemos utilizar el **rango intercuartílico (IQR)**.


## Detección de outliers mediante el rango intercuartílico

Una forma habitual de detectar valores atípicos en una variable numérica consiste en utilizar los **cuartiles**.

El primer cuartil (`Q1`) deja por debajo aproximadamente al 25 % de los datos, mientras que el tercer cuartil (`Q3`) deja por debajo aproximadamente al 75 %.

La diferencia entre ambos se denomina **rango intercuartílico**:

$$
IQR = Q3 - Q1
$$

Un criterio frecuente considera potenciales outliers a los valores que se encuentran fuera del intervalo:

$$
Q1 - 1.5 \times IQR
$$

y

$$
Q3 + 1.5 \times IQR
$$

Este método no determina que un dato sea necesariamente incorrecto. Solamente permite identificar valores suficientemente alejados de la zona central de la distribución como para justificar una inspección adicional.

En Pandas podemos obtener los cuartiles mediante:

```python
df["Salary"].quantile(0.25)
df["Salary"].quantile(0.75)
```

Calcularemos `Q1`, `Q3`, el rango intercuartílico y los límites inferior y superior resultantes.


In [ ]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Límite inferior:", limite_inferior)
print("Límite superior:", limite_superior)

Q1: 68254.9475
Q3: 101245.38
IQR: 32990.43250000001
Límite inferior: 18769.29874999998
Límite superior: 150731.02875000003


Obtuvimos:

```text
Q1 = 68254.95
Q3 = 101245.38
IQR = 32990.43
```

Aplicando el criterio de `1.5 × IQR`, los límites resultaron aproximadamente:

```text
Límite inferior = 18769.30
Límite superior = 150731.03
```

Según este criterio, cualquier salario menor que `18769.30` o mayor que `150731.03` puede considerarse un **valor atípico potencial**.

> Esto no significa automáticamente que esos registros sean erróneos. El método solamente nos indica que se encuentran suficientemente alejados de la zona central de la distribución como para justificar una revisión.

El siguiente paso será identificar exactamente qué salarios quedan fuera de esos límites.


### Selección de salarios fuera de los límites

Para localizar los posibles outliers podemos construir una condición lógica:

```python
(df["Salary"] < limite_inferior) | (df["Salary"] > limite_superior)
```

El símbolo:

```python
|
```

representa una operación lógica **OR**: la condición se cumple si el salario está por debajo del límite inferior **o** por encima del límite superior.

Utilizaremos esa condición para seleccionar solamente las filas que cumplen alguno de esos dos casos.


In [ ]:
outliers_salary = df[
    (df["Salary"] < limite_inferior) |
    (df["Salary"] > limite_superior)
]

outliers_salary[["Employee_ID", "Salary"]].sort_values("Salary")

,Employee_ID,Salary
715,EMP1715,-45000.0
573,EMP1573,-1.0
735,EMP1735,0.0
808,EMP1808,175.0
988,EMP1988,1200.0
578,EMP1578,500000.0
288,EMP1288,950000.0
91,EMP1091,999999.0
240,EMP1240,1800000.0
374,EMP1374,2500000.0


Aplicando los límites calculados mediante el rango intercuartílico, encontramos **10 registros** cuyos salarios quedan fuera del intervalo considerado habitual.

Los cinco primeros se encuentran por debajo del límite inferior calculado, mientras que los cinco últimos superan el límite superior.

En este caso, además, algunos valores resultan claramente problemáticos desde el punto de vista semántico: por ejemplo, un salario negativo o igual a cero difícilmente represente un salario válido.

En cambio, los valores muy altos requieren algo más de cautela. Un valor extremo puede ser perfectamente real en determinados contextos.

Por eso conviene distinguir entre dos conceptos:

> **outlier** no significa necesariamente **error**.

El criterio IQR nos ayuda a localizar observaciones que merecen revisión, pero la decisión final debería considerar también el significado de la variable y el contexto del problema.

Para este dataset didáctico adoptaremos una regla práctica: los valores detectados fuera de los límites del IQR serán tratados como valores inválidos y reemplazados por `NaN`.

De esta manera podremos gestionar posteriormente todos los salarios faltantes o inválidos mediante una estrategia común.


### Reemplazo de los salarios atípicos

Utilizaremos la misma condición lógica que empleamos para detectarlos:

```python
(df["Salary"] < limite_inferior) | (df["Salary"] > limite_superior)
```

Con `loc[]` seleccionaremos solamente esas filas y la columna `Salary`. Luego asignaremos:

```python
pd.NA
```

para indicar que esos valores deben considerarse ausentes o no válidos.


In [ ]:
df.loc[
    (df["Salary"] < limite_inferior) |
    (df["Salary"] > limite_superior),
    "Salary"
] = pd.NA

df["Salary"].isna().sum()

np.int64(34)

Después de reemplazar por `NaN` los salarios que quedaban fuera de los límites definidos mediante el criterio IQR, la columna `Salary` quedó con 34 valores ausentes.

Antes de esta operación habíamos observado que `Salary` tenía 24 valores ausentes. Por lo tanto, **se agregaron 10 nuevos valores ausentes**.


Estos corresponden exactamente a los 10 salarios que habíamos identificado como outliers mediante el criterio utilizado.

De esta manera, los valores faltantes originales y los valores considerados inválidos quedaron representados de una forma común mediante `NaN`.

Más adelante tendremos que decidir qué estrategia utilizar para tratar esos valores ausentes. Por ahora continuaremos explorando otras columnas del dataset antes de realizar imputaciones o eliminaciones definitivas.


---

## Inspección de la variable categórica `Status`

Hasta ahora trabajamos principalmente con variables numéricas. Ahora comenzaremos a revisar las variables categóricas. En este tipo de columnas, uno de los problemas más frecuentes es encontrar categorías escritas de formas ligeramente diferentes, por ejemplo:

```text
Active
active
ACTIVE
Active
```

Aunque para una persona puedan representar la misma categoría, Pandas las considera valores distintos. Para inspeccionar qué valores aparecen en `Status` utilizaremos:

```python
value_counts()
```

Este método cuenta cuántas veces aparece cada valor de una columna. Además, utilizaremos:

```python
dropna=False
```

para que los valores ausentes también aparezcan en el recuento. De esta manera podremos observar tanto las categorías existentes como posibles inconsistencias de escritura.


In [ ]:
df["Status"].value_counts(dropna=False)


,count
Status,
Pending,346
Active,342
Inactive,301
NaN,8
PENDING,1
Unknown,1
ACTIVE,1
inactive,1
actIVE,1


El recuento muestra tres categorías que aparecen con mucha mayor frecuencia:

```text
Pending   → 346
Active    → 342
Inactive  → 301
```

También encontramos **8 valores ausentes**.

Sin embargo, aparecen además numerosas variantes con muy pocos registros. Algunas parecen ser simplemente diferencias en el uso de mayúsculas y minúsculas, mientras que otras contienen posibles errores de escritura.

Hay además un detalle interesante: en la salida aparecen algunas etiquetas aparentemente iguales más de una vez, como `Active`, `ACTIVE` o `pending`.

Si `value_counts()` las muestra por separado, significa que para Pandas **no son exactamente la misma cadena de texto**, aunque visualmente puedan parecer iguales en la tabla.

Antes de corregir los valores conviene inspeccionarlos de una forma que permita ver con mayor claridad posibles espacios u otros caracteres que normalmente pasan inadvertidos.


### Visualización de las cadenas tal como están almacenadas

La función `repr()` permite obtener una representación más explícita de una cadena de texto. Por ejemplo, si un valor contiene un espacio al final, `repr()` permite distinguir `Active` de `Active ` aunque ambos puedan verse prácticamente iguales al mostrarlos normalmente.

Aplicaremos `repr()` a cada valor diferente de `Status` para examinar con mayor precisión cómo están almacenadas las categorías.


In [ ]:
for valor in df["Status"].unique():
    print(repr(valor))

'Active'
'Pending'
'Inactive'
nan
'PENDING '
'Unknown'
'ACTIVE'
' inactive'
'actIVE'
'Pendng'
'INACTIVE'
'Active '
'ACTIVE '
'Inactive '
'active'
' pending '
'Actve'
'pending'
'In Active'


La representación obtenida con `repr()` muestra que varias categorías difieren únicamente por detalles de formato.

Por ejemplo:

```text
'Active'
'Active '
'ACTIVE'
'ACTIVE '
'active'
'actIVE'
```

También ocurre algo similar con:

```text
'Pending'
'PENDING '
' pending '
'pending'
```

y con:

```text
'Inactive'
'Inactive '
'INACTIVE'
' inactive'
```

Esto confirma que existen diferencias de:

* mayúsculas y minúsculas;
* espacios al comienzo o al final;
* errores de escritura, como `'Actve'` o `'Pendng'`;
* variantes más difíciles de interpretar automáticamente, como `'In Active'`;
* valores como `'Unknown'`, cuyo significado no coincide con ninguna de las categorías principales.

Para limpiar correctamente esta columna conviene avanzar en etapas.

Primero podemos resolver las diferencias puramente de formato, eliminando espacios sobrantes y unificando el uso de mayúsculas y minúsculas. Después volveremos a inspeccionar las categorías restantes para tratar los errores de escritura de forma explícita.


### Normalización básica de texto

Para eliminar espacios al principio y al final de cada cadena podemos utilizar:

```python
.str.strip()
```

Después podemos aplicar:

```python
.str.title()
```

para convertir cada categoría a un formato uniforme, con la primera letra en mayúscula. Por ejemplo:

```text
' active '  →  'Active'
'PENDING '  →  'Pending'
'inactive'  →  'Inactive'
```

Estas operaciones corrigen diferencias de formato, pero no errores ortográficos como `'Actve'` o `'Pendng'`.


In [ ]:
df["Status"] = df["Status"].str.strip().str.title()

df["Status"].value_counts(dropna=False)

,count
Status,
Pending,349
Active,347
Inactive,304
NaN,8
Unknown,1
Pendng,1
Actve,1
In Active,1


Las variantes que solo diferían por espacios o por el uso de mayúsculas y minúsculas quedaron unificadas.

Ahora aparecen principalmente:

```text
Pending   → 349
Active    → 347
Inactive  → 304
```

También permanecen:

```text
Unknown   → 1
Pendng    → 1
Actve     → 1
In Active → 1
NaN       → 8
```

Esto muestra una diferencia importante entre dos tipos de problemas:

* las inconsistencias de formato pueden corregirse automáticamente;
* los errores de escritura o los valores ambiguos requieren una decisión explícita.

Por ejemplo, `Pendng` parece corresponder a `Pending` y `Actve` a `Active`.

En cambio, `Unknown` no representa una de las categorías habituales y `In Active` necesita interpretarse antes de decidir cómo corregirlo.


### Corrección explícita de categorías

Para corregir valores puntuales podemos utilizar el método `.replace()`

Este método permite indicar qué valor debe ser reemplazado por otro. En este caso corregiremos únicamente aquellas variantes cuya interpretación resulta clara:

```text
Pendng    → Pending
Actve     → Active
In Active → Inactive
```

El valor `Unknown` no será asignado arbitrariamente a ninguna categoría. Lo convertiremos en un valor ausente para indicar que no conocemos su estado real.


In [ ]:
df["Status"] = df["Status"].replace({
    "Pendng": "Pending",
    "Actve": "Active",
    "In Active": "Inactive",
    "Unknown": pd.NA
})

df["Status"].value_counts(dropna=False)

,count
Status,
Pending,350
Active,348
Inactive,305
NaN,8
<NA>,1


Las categorías válidas quedaron reducidas a:

```text
Pending
Active
Inactive
```

También observamos dos representaciones de valores ausentes:

```text
NaN
<NA>
```

Ambas indican ausencia de información, aunque Pandas puede mostrarlas de manera diferente según cómo se haya generado el valor faltante.

En este caso, los 8 valores `NaN` ya estaban presentes en la columna, mientras que el valor `<NA>` corresponde al registro `Unknown` que acabamos de reemplazar.

Por lo tanto, podemos considerar que `Status` contiene ahora **9 valores ausentes en total**.


### Comprobación de los valores ausentes

Aunque `value_counts(dropna=False)` pueda mostrar `NaN` y `<NA>` por separado, el método `isna()` considera ambas representaciones como valores ausentes.

Podemos utilizarlo para contar cuántos faltantes tiene realmente la columna `Status`.


In [ ]:
df["Status"].isna().sum()

np.int64(9)

Esto confirma que la columna `Status` contiene **9 valores ausentes en total**. La columna quedó entonces con tres categorías válidas:

```text
Pending
Active
Inactive
```

y 9 valores cuya categoría se desconoce.

Por ahora no vamos a imputar esos valores. Continuaremos revisando las demás variables categóricas antes de decidir cómo tratar los faltantes.


---

## Inspección de `Department_Region`

La columna `Department_Region` parece contener información categórica relacionada con el área de trabajo y la región. Antes de modificarla, conviene observar qué valores diferentes aparecen y con qué frecuencia.

Utilizaremos nuevamente `value_counts(dropna=False)` para contar cada categoría e incluir también los valores ausentes.

En esta etapa buscamos detectar posibles diferencias de escritura, espacios, mayúsculas o formatos inconsistentes.


In [ ]:
df["Department_Region"].value_counts(dropna=False)

,count
Department_Region,
HR-Florida,41
DevOps-California,35
Sales-Nevada,34
Sales-Florida,33
Admin-California,33
Finance-Illinois,33
HR-New York,33
DevOps-New York,33
DevOps-Florida,33


La salida de `value_counts()` muestra muchas combinaciones que se repiten con frecuencia, por ejemplo:

```text
HR-Florida
DevOps-California
Sales-Nevada
Finance-Illinois
Cloud Tech-Texas
```

También aparecen **8 valores ausentes**.

Además, vemos varias categorías con una sola aparición que parecen ser variantes inconsistentes de categorías ya existentes, por ejemplo:

```text
Finance - Texas
CloudTech-Texas
Finance_texas
DEVOPS-California
Sales - Nevada
Dev Ops-California
DevOps California
HR_Florida
Sales- nevada
```

También aparecen posibles errores de escritura:

```text
Financ-Texas
Sales-Nevadaa
```

En esta columna hay, por lo tanto, varios tipos de inconsistencias:

* diferencias de mayúsculas y minúsculas;
* espacios adicionales;
* uso de `_` en lugar de `-`;
* ausencia del separador;
* palabras unidas o separadas de manera distinta;
* errores ortográficos.

Antes de corregir los valores conviene observar cómo están almacenadas exactamente algunas de estas categorías.


### Visualización exacta de las categorías

Como hicimos anteriormente con `Status`, podemos utilizar `repr()` para ver espacios u otros caracteres que no siempre resultan evidentes en una tabla.

En lugar de mostrar todos los registros, recorreremos solamente los valores únicos de `Department_Region`.


In [ ]:
for valor in df["Department_Region"].unique():
    print(repr(valor))

'DevOps-California'
'Finance-Texas'
'Admin-Nevada'
'Cloud Tech-Florida'
'Sales-Texas'
'DevOps-New York'
'Cloud Tech-New York'
'HR-New York'
'Finance-California'
'Sales-Florida'
'DevOps-Illinois'
'Cloud Tech-Nevada'
'Admin-Illinois'
'Cloud Tech-Illinois'
'Sales-Illinois'
'Finance-Nevada'
'Admin-Texas'
'Sales-New York'
'Finance-Florida'
'Admin-California'
'HR-Texas'
'HR-California'
'HR-Nevada'
'Cloud Tech-Texas'
'Sales-California'
'HR-Illinois'
'Admin-New York'
'Admin-Florida'
'HR-Florida'
'Sales-Nevada'
'Finance-New York'
'DevOps-Florida'
'DevOps-Texas'
'Finance-Illinois'
'Cloud Tech-California'
'Finance - Texas'
'Finance_texas'
'DevOps-Nevada'
'CloudTech-Texas'
'DEVOPS-California'
' Admin-Nevada '
'Sales - Nevada'
nan
'Financ-Texas'
'Sales-Nevadaa'
'Dev Ops-California'
'Cloud Tech-Texas '
'DevOps California'
' HR-Florida'
'Admin-nevada'
'HR_Florida'
'Sales- nevada'


La salida de `repr()` confirma varios tipos de inconsistencias. Por ejemplo, aparecen espacios al comienzo o al final:

```text
' Admin-Nevada '
'Cloud Tech-Texas '
' HR-Florida'
```

También encontramos separadores distintos:

```text
'Finance_texas'
'HR_Florida'
```

y casos en los que directamente falta el guion:

```text
'DevOps California'
```

Además aparecen diferencias de mayúsculas y minúsculas:

```text
'DEVOPS-California'
'Admin-nevada'
```

y formas inconsistentes de escribir algunos departamentos:

```text
'CloudTech-Texas'
'Dev Ops-California'
```

Finalmente, hay errores de escritura más claros:

```text
'Financ-Texas'
'Sales-Nevadaa'
```

Como los problemas son de distinta naturaleza, conviene no intentar resolverlos todos con una sola transformación.

Primero corregiremos las diferencias más mecánicas de formato: espacios sobrantes, uso de guiones bajos y mayúsculas/minúsculas.


### Primera normalización de `Department_Region`

Aplicaremos tres transformaciones sencillas:

* `.str.strip()` para eliminar espacios al principio y al final;
* `.str.replace("_", "-", regex=False)` para reemplazar guiones bajos por guiones medios;
* `.str.title()` para unificar el uso de mayúsculas y minúsculas.

Estas operaciones pueden corregir varias inconsistencias de formato, aunque todavía no resolverán errores como `Financ-Texas`, `Sales-Nevadaa` o casos donde falte el separador.


In [ ]:
df["Department_Region"] = (
    df["Department_Region"]
    .str.strip()
    .str.replace("_", "-", regex=False)
    .str.title()
)

df["Department_Region"].value_counts(dropna=False)

,count
Department_Region,
Hr-Florida,43
Devops-California,36
Admin-Nevada,34
Sales-Nevada,34
Sales-Florida,33
Admin-California,33
Devops-Florida,33
Hr-New York,33
Finance-Illinois,33


Vemos que varias inconsistencias se redujeron. Por ejemplo, los valores con espacios al comienzo o al final quedaron normalizados, y los guiones bajos fueron reemplazados por guiones medios.

Sin embargo, todavía aparecen categorías que requieren una corrección adicional:

```text
Finance - Texas
Cloudtech-Texas
Sales - Nevada
Financ-Texas
Sales-Nevadaa
Dev Ops-California
Devops California
Sales- Nevada
```

También podemos observar que `str.title()` modificó algunas formas de escritura:

```text
HR      → Hr
DevOps  → Devops
```

Esto muestra que una normalización automática puede resolver ciertos problemas, pero también puede alterar convenciones de escritura que quizá queramos conservar.

Por eso, el siguiente paso será realizar correcciones explícitas sobre las categorías que todavía presentan inconsistencias.


### Correcciones puntuales en `Department_Region`

Utilizaremos nuevamente `replace()` para corregir únicamente valores cuya interpretación es clara.

En esta etapa normalizaremos:

```text
Finance - Texas   → Finance-Texas
Cloudtech-Texas   → Cloud Tech-Texas
Sales - Nevada    → Sales-Nevada
Financ-Texas      → Finance-Texas
Sales-Nevadaa     → Sales-Nevada
Dev Ops-California → DevOps-California
Devops California → DevOps-California
Sales- Nevada     → Sales-Nevada
```

También restauraremos algunas convenciones de escritura que queremos mantener:

```text
Hr      → HR
Devops  → DevOps
```


In [ ]:
df["Department_Region"] = df["Department_Region"].replace({
    "Finance - Texas": "Finance-Texas",
    "Cloudtech-Texas": "Cloud Tech-Texas",
    "Sales - Nevada": "Sales-Nevada",
    "Financ-Texas": "Finance-Texas",
    "Sales-Nevadaa": "Sales-Nevada",
    "Dev Ops-California": "DevOps-California",
    "Devops California": "DevOps-California",
    "Sales- Nevada": "Sales-Nevada"
})

df["Department_Region"] = (
    df["Department_Region"]
    .str.replace(r"^Hr-", "HR-", regex=True)
    .str.replace(r"^Devops-", "DevOps-", regex=True)
)

df["Department_Region"].value_counts(dropna=False)

,count
Department_Region,
HR-Florida,43
DevOps-California,38
Sales-Nevada,37
Admin-Nevada,34
DevOps-New York,33
Finance-Illinois,33
DevOps-Florida,33
Sales-Florida,33
HR-New York,33


Ahora, la columna `Department_Region` quedó reducida a combinaciones consistentes como:

```text
HR-Florida
DevOps-California
Sales-Nevada
Finance-Texas
Cloud Tech-Texas
```

Las variantes problemáticas que habíamos detectado ya no aparecen en el recuento. También se restauraron las convenciones de escritura:

```text
HR
DevOps
```

En la columna permanecen **8 valores ausentes**, que por ahora no vamos a completar. En este punto `Department_Region` quedó normalizada desde el punto de vista de escritura.


## Separación de `Department_Region`

La columna `Department_Region` contiene en realidad dos datos diferentes:

* el departamento;
* la región.

Por ejemplo:

```text
DevOps-California
```

combina:

```text
Department = DevOps
Region = California
```

Cuando una columna contiene más de una característica, puede resultar conveniente separarla en variables independientes. Para hacerlo utilizaremos:

```python
.str.split("-", n=1, expand=True)
```

El método `split()` divide una cadena utilizando un separador. En este caso:

```text
"-"
```

será el separador. El argumento:

```python
n=1
```

indica que queremos realizar como máximo una división. Y:

```python
expand=True
```

hace que el resultado se devuelva en columnas separadas, en lugar de como una lista dentro de cada celda.


In [ ]:
df[["Department", "Region"]] = (
    df["Department_Region"]
    .str.split("-", n=1, expand=True)
)

df[["Department_Region", "Department", "Region"]].head(10)

,Department_Region,Department,Region
0,DevOps-California,DevOps,California
1,Finance-Texas,Finance,Texas
2,Admin-Nevada,Admin,Nevada
3,Admin-Nevada,Admin,Nevada
4,Cloud Tech-Florida,Cloud Tech,Florida
5,Sales-Texas,Sales,Texas
6,Admin-Nevada,Admin,Nevada
7,Cloud Tech-Florida,Cloud Tech,Florida
8,Admin-Nevada,Admin,Nevada
9,DevOps-New York,DevOps,New York


Obtuvimos dos nuevas columnas:

```text
Department
Region
```

En las primeras filas observadas, la división se realizó de la forma esperada.

La columna original `Department_Region` todavía permanece en el DataFrame. Por ahora la conservaremos, ya que puede resultar útil para comparar los datos originales con las nuevas variables creadas.

Más adelante podremos decidir si conviene eliminarla para evitar mantener información redundante.


### Comprobación de las nuevas columnas

Después de crear nuevas variables a partir de una columna existente, conviene verificar qué valores contienen.

Utilizaremos `value_counts(dropna=False)` para revisar por separado:

* las categorías de `Department`;
* las categorías de `Region`;
* los valores ausentes que puedan haberse propagado desde `Department_Region`.


In [ ]:
print("Departamentos:")
print(df["Department"].value_counts(dropna=False))

print("\nRegiones:")
print(df["Region"].value_counts(dropna=False))

Departamentos:
Department
DevOps        189
Sales         174
HR            171
Finance       168
Admin         159
Cloud Tech    143
NaN             8
Name: count, dtype: int64

Regiones:
Region
California    187
Florida       182
Nevada        166
Illinois      159
New York      156
Texas         154
NaN             8
Name: count, dtype: int64


La revisión de las nuevas columnas muestra que `Department` contiene seis categorías:

```text
DevOps        → 189
Sales         → 174
HR            → 171
Finance       → 168
Admin         → 159
Cloud Tech    → 143
NaN           → 8
```

Por su parte, `Region` contiene seis categorías:

```text
California → 187
Florida    → 182
Nevada     → 166
Illinois   → 159
New York   → 156
Texas      → 154
NaN        → 8
```

En ambas columnas aparecen **8 valores ausentes**.

Esto coincide con los 8 valores ausentes que ya habíamos observado en `Department_Region`, por lo que la separación no generó nuevos faltantes: simplemente propagó la ausencia de información original a las dos variables creadas.

Además, en esta salida no aparecen nuevas variantes de escritura dentro de `Department` o `Region`.

Podemos considerar entonces que la separación de `Department_Region` fue satisfactoria.


## Inspección de `Performance_Score`

La columna `Performance_Score` representa una evaluación del desempeño de cada empleado.

Antes de utilizarla debemos comprobar qué categorías contiene y si existen diferencias de escritura o valores inconsistentes.

Como en los casos anteriores, utilizaremos:

```python
value_counts(dropna=False)
```

para contar las apariciones de cada categoría e incluir también los valores ausentes.

En esta etapa solamente inspeccionaremos los valores. Todavía no realizaremos ninguna transformación.


In [ ]:
df["Performance_Score"].value_counts(dropna=False)

,count
Performance_Score,
Good,265
Average,260
Excellent,260
Poor,207
NaN,9
Good,1
good,1
average,1
Exellent,1


La salida muestra cuatro categorías que aparecen con mucha mayor frecuencia:

```text
Good       → 265
Average    → 260
Excellent  → 260
Poor       → 207
```

También encontramos **9 valores ausentes**.

Además aparecen algunas variantes con una sola aparición:

```text
good
average
EXCELLENT
excellent
POOR
```

y otras que parecen contener errores de escritura:

```text
Exellent
Averge
```

También aparece:

```text
Very Good
```

que merece una revisión especial. A diferencia de `Exellent` o `Averge`, no parece simplemente un error ortográfico: podría representar una categoría adicional.

Igual que hicimos con otras columnas, antes de decidir cómo tratar estos casos conviene inspeccionar los valores exactamente como están almacenados, especialmente porque algunas categorías aparentemente iguales aparecen separadas en el recuento.


### Visualización exacta de las categorías

Como hicimos con `Status`, utilizaremos `repr()` para comprobar si existen espacios al comienzo o al final de algunas cadenas.

Esto permite distinguir, por ejemplo `Good` de `Good ` aunque visualmente puedan parecer iguales en una tabla.


In [ ]:
for valor in df["Performance_Score"].unique():
    print(repr(valor))

'Average'
'Excellent'
'Good'
'Poor'
'Good '
' average'
'good'
'Exellent'
nan
'EXCELLENT'
'Very Good'
'Excellent '
'Averge'
'excellent'
'POOR'
'Poor '


La salida de `repr()` confirma que algunas categorías difieren solamente por espacios o por el uso de mayúsculas y minúsculas y otras que nuevamente parecen diferenciarse solamente por un espacio y el uso de mayúsculas.

En cambio, aparecen otros valores que necesitan una corrección explícita:

```text
'Exellent'
'Averge'
```

que parecen ser errores de escritura. Finalmente `'Very Good'`. Este valor no es simplemente una variante de formato de las categorías anteriores. Podría representar una categoría adicional, por lo que no conviene reemplazarlo automáticamente sin establecer antes un criterio.

Primero corregiremos las diferencias puramente de formato y luego volveremos a inspeccionar las categorías resultantes.


### Normalización básica de `Performance_Score`

Aplicaremos nuevamente dos operaciones sobre las cadenas de texto `.str.strip()` para eliminar espacios al comienzo o al final, y `.str.title()` para unificar el uso de mayúsculas y minúsculas.

Estas transformaciones permitirán agrupar variantes como:

```text
'Good '
'good'
```

en una única categoría. Todavía no corregiremos los errores ortográficos ni decidiremos qué hacer con `Very Good`.


In [ ]:
df["Performance_Score"] = (
    df["Performance_Score"]
    .str.strip()
    .str.title()
)

df["Performance_Score"].value_counts(dropna=False)

,count
Performance_Score,
Good,267
Excellent,263
Average,261
Poor,209
NaN,9
Exellent,1
Very Good,1
Averge,1


Las categorías principales quedaron agrupadas correctamente:

```text
Good       → 267
Excellent  → 263
Average    → 261
Poor       → 209
```

También permanecen **9 valores ausentes**. Las únicas categorías que todavía requieren una decisión son:

```text
Exellent   → 1
Averge     → 1
Very Good  → 1
```

Como no tenemos información adicional que permita determinar cómo debería clasificarse ese ultimo valor, evitaremos asignarlo arbitrariamente a `Good` o `Excellent`. Lo trataremos como un valor ausente.


### Corrección de los valores restantes

Utilizaremos `replace()` para realizar tres cambios explícitos:

```text
Exellent  → Excellent
Averge    → Average
Very Good → valor ausente
```

Las dos primeras correcciones recuperan categorías cuya interpretación es clara.

En el último caso utilizaremos `pd.NA`, ya que el dataset no nos permite decidir con certeza a cuál de las categorías existentes debería pertenecer `Very Good`.

Después volveremos a contar las categorías para comprobar el resultado.



In [ ]:
df["Performance_Score"] = df["Performance_Score"].replace({
    "Exellent": "Excellent",
    "Averge": "Average",
    "Very Good": pd.NA
})

df["Performance_Score"].value_counts(dropna=False)

,count
Performance_Score,
Good,267
Excellent,264
Average,262
Poor,209
NaN,9
<NA>,1


Después de corregir los errores de escritura y transformar `Very Good` en un valor ausente, la columna quedó con cuatro categorías principales:

```text
Good       → 267
Excellent  → 264
Average    → 262
Poor       → 209
```

Además aparecen:

```text
NaN  → 9
<NA> → 1
```

Como vimos anteriormente, ambas representaciones corresponden a valores ausentes. Por lo tanto, `Performance_Score` contiene ahora **10 valores faltantes en total**.

La columna quedó normalizada en cuatro categorías. Estas categorías tienen además un **orden natural**, ya que representan distintos niveles de desempeño. Esta característica será importante más adelante cuando preparemos las variables categóricas para Machine Learning.


### Comprobación de los valores ausentes

Utilizaremos nuevamente `isna().sum()` para comprobar cuántos valores faltantes reconoce Pandas en `Performance_Score`, independientemente de que se muestren como `NaN` o `<NA>`.


In [ ]:
df["Performance_Score"].isna().sum()

np.int64(10)

La columna contiene 10 valores ausentes. Esto confirma que los 9 valores faltantes originales más el valor `Very Good` que convertimos en ausente están siendo reconocidos correctamente por Pandas.


---

## Revisión de `Remote_Work`

La columna `Remote_Work` fue cargada como `object`, por lo que conviene revisar qué valores contiene antes de decidir si debe transformarse a un tipo booleano.


In [ ]:
df["Remote_Work"].value_counts(dropna=False)

,count
Remote_Work,
TRUE,501
FALSE,496
NaN,5
FALSE,1
No,1
1,1
0,1
Y,1
true,1


### Conversión de `Remote_Work` a valores booleanos

Primero normalizaremos los textos eliminando espacios y convirtiéndolos a minúsculas. Luego utilizaremos `map()` para asociar cada representación con un valor lógico:

```text
true, yes, y, 1  → True
false, no, n, 0  → False
```

Finalmente convertiremos la columna al tipo:

```python
boolean
```

Este tipo de Pandas permite almacenar tres posibilidades:

```text
True
False
<NA>
```

por lo que resulta adecuado para una variable binaria que además puede contener valores ausentes.


In [ ]:
df["Remote_Work"] = (
    df["Remote_Work"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "true": True,
        "yes": True,
        "y": True,
        "1": True,
        "false": False,
        "no": False,
        "n": False,
        "0": False
    })
    .astype("boolean")
)

df["Remote_Work"].value_counts(dropna=False)

,count
Remote_Work,
True,506
False,501
<NA>,5


La columna quedó reducida a tres posibilidades:

```text
True   → 506
False  → 501
<NA>   → 5
```

Las distintas formas de representar respuestas afirmativas y negativas quedaron unificadas correctamente.

Además, los **5 valores ausentes** se conservaron como tales.

`Remote_Work` queda ahora representada mediante el tipo booleano de Pandas, adecuado para una variable con valores `True`, `False` y datos faltantes.


---

## Revisión de `Join_Date`

La columna `Join_Date` contiene las fechas de ingreso de los empleados, pero Pandas la cargó inicialmente como `object`.

Antes de convertirla a un tipo de fecha conviene inspeccionar algunos de sus valores, especialmente porque un mismo dataset puede contener fechas escritas con formatos diferentes o incluso valores inválidos.

Vamos a observar una muestra de los valores almacenados en esta columna.


In [ ]:
df["Join_Date"].dropna().sample(20, random_state=42).tolist()

['10/16/2021',
 '2/18/2023',
 '4/5/2023',
 '6/10/2024',
 '1/10/2020',
 '4/8/2022',
 '8/30/2023',
 '6/6/2023',
 '2/1/2023',
 '9/16/2024',
 '12/23/2024',
 '1/5/2023',
 '5/12/2020',
 '3/5/2021',
 '5/24/2023',
 '11/29/2023',
 '1/1/2020',
 '9/24/2024',
 '4/17/2022',
 '8/19/2022']

En la muestra obtenida aparecen fechas como:

```text
10/16/2021
4/5/2023
12/23/2024
1/1/2020
```

Todas las fechas mostradas presentan una estructura similar.

Sin embargo, estamos observando solamente **20 valores de una columna con más de mil registros**, por lo que esta muestra no alcanza para asegurar que todas las fechas estén escritas de la misma manera.

Una forma más sistemática de revisar la columna consiste en intentar convertir sus valores al tipo de fecha de Pandas y comprobar cuáles no pueden interpretarse correctamente.

Para hacerlo utilizaremos:

```python
pd.to_datetime()
```

El argumento:

```python
errors="coerce"
```

hace que los valores que no puedan convertirse se transformen en `NaT` (*Not a Time*), que es la representación de Pandas para una fecha ausente o inválida.

Además utilizaremos:

```python
format="mixed"
```

para permitir que Pandas intente interpretar individualmente distintos formatos de fecha que puedan aparecer en la columna.

Por ahora guardaremos el resultado en una variable auxiliar, sin modificar todavía `Join_Date`.


In [ ]:
fechas_convertidas = pd.to_datetime(
    df["Join_Date"],
    errors="coerce",
    format="mixed"
)

print("Valores ausentes originales:", df["Join_Date"].isna().sum())
print("Valores ausentes después de intentar la conversión:", fechas_convertidas.isna().sum())

Valores ausentes originales: 6
Valores ausentes después de intentar la conversión: 14


Antes de convertir la columna había 6 valores ausentes.
Después de intentar interpretar todos los valores como fechas obtuvimos 14 valores ausentes.

Esto significa que **8 valores que originalmente no estaban vacíos no pudieron convertirse correctamente a fecha**.

Por lo tanto, en `Join_Date` existen registros con contenido que Pandas no reconoce como una fecha válida.

Antes de modificar la columna original, conviene identificar exactamente cuáles son esos valores.


Queremos seleccionar los casos en los que:

* `Join_Date` originalmente tenía algún valor;
* pero la conversión produjo `NaT`.

Para combinar ambas condiciones utilizaremos el operador `&`, que representa un **AND lógico**.


In [ ]:
fechas_invalidas = df[
    df["Join_Date"].notna() &
    fechas_convertidas.isna()
]

fechas_invalidas[["Employee_ID", "Join_Date"]]

,Employee_ID,Join_Date
321,EMP1321,Feb-31-2021
396,EMP1396,31/02/2023
492,EMP1492,99/99/9999
553,EMP1553,00/12/2022
629,EMP1629,202A-05-10
669,EMP1669,2022/02/30
767,EMP1767,not_a_date
953,EMP1953,2023-13-04



Vemos que en algunos casos el problema es una fecha imposible, por ejemplo:

```text
31/02/2023
2022/02/30
Feb-31-2021
```

En otros aparecen componentes inválidos:

```text
99/99/9999
00/12/2022
2023-13-04
```

También encontramos valores que directamente no representan una fecha válida:

```text
202A-05-10
not_a_date
```

Como no tenemos información que permita reconstruir correctamente esas fechas, las trataremos como valores ausentes.

La variable auxiliar `fechas_convertidas` ya contiene esos casos como `NaT`, por lo que podemos utilizarla para reemplazar la columna original. De esta manera, `Join_Date` dejará de ser una columna de texto y pasará a utilizar el tipo de fecha de Pandas.

Los valores que no pudieron interpretarse correctamente permanecerán como `NaT`.



In [ ]:
df["Join_Date"] = fechas_convertidas

df["Join_Date"].dtype, df["Join_Date"].isna().sum()

(dtype('<M8[ns]'), np.int64(14))

La columna quedó con tipo `datetime64[ns]`. Esto confirma que Pandas ya la reconoce como una variable de fecha. Además, contiene 14 valores ausentes. Estos 14 casos corresponden a los 6 valores que ya estaban ausentes más los 8 valores que no pudieron interpretarse como fechas válidas.

A partir de este punto podremos utilizar las herramientas específicas de Pandas para trabajar con fechas, por ejemplo extraer el año, el mes o calcular antigüedad.


---

## Revisión de `Email`

La columna `Email` contiene direcciones de correo electrónico.

En este caso no buscamos convertir el tipo de dato, sino detectar valores que puedan tener errores de formato.

Una validación sencilla consiste en comprobar si cada dirección contiene una estructura mínima del tipo:

```text
texto@texto.dominio
```

No será una validación exhaustiva de todos los correos posibles, pero sí nos permitirá localizar errores evidentes.

Utilizaremos `str.match()` con una expresión regular sencilla.

La expresión:

```python
^[^@\s]+@[^@\s]+\.[^@\s]+$
```

comprueba, de manera básica, que exista:

* texto antes de `@`;
* un separador `@`;
* texto después de `@`;
* un punto antes del dominio final;
* ausencia de espacios.

Además utilizaremos:

```python
na=False
```

para evitar que los valores ausentes generen problemas durante la comparación.


In [ ]:
patron_email = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

emails_invalidos = df[
    df["Email"].notna() &
    ~df["Email"].str.match(patron_email, na=False)
]

emails_invalidos[["Employee_ID", "Email"]]

,Employee_ID,Email
189,EMP1189,mary@@example.com
206,EMP1206,@example.com
228,EMP1228,carol.davis@example.com
330,EMP1330,no_email
388,EMP1388,lisa.white@ example.com
552,EMP1552,grace.brownexample.com
722,EMP1722,dave.wilson@example.com
838,EMP1838,john doe@example.com
861,EMP1861,bob.smith@
959,EMP1959,eva.miller@example


La validación encontró varios valores claramente problemáticos, por ejemplo:

```text
mary@@example.com
@example.com
no_email
lisa.white@ example.com
grace.brownexample.com
john doe@example.com
bob.smith@
eva.miller@example
```

Sin embargo, también aparecen algunos correos que visualmente parecen correctos, como:

```text
carol.davis@example.com
dave.wilson@example.com
```

Esto sugiere que podrían contener espacios u otros caracteres poco visibles. Antes de corregir la columna conviene inspeccionar esos valores utilizando nuevamente `repr()`.


In [ ]:
for valor in emails_invalidos["Email"]:
    print(repr(valor))

'mary@@example.com'
'@example.com'
' carol.davis@example.com'
'no_email'
'lisa.white@ example.com'
'grace.brownexample.com'
'dave.wilson@example.com '
'john doe@example.com'
'bob.smith@'
'eva.miller@example'


Algunos valores solamente tienen espacios sobrantes:

```text
' carol.davis@example.com'
'dave.wilson@example.com '
```

Estos casos pueden corregirse fácilmente eliminando los espacios al comienzo y al final de la cadena. En cambio, otros valores presentan errores de estructura, por ejemplo:

```text
'mary@@example.com'
'@example.com'
'no_email'
'lisa.white@ example.com'
'grace.brownexample.com'
'john doe@example.com'
'bob.smith@'
'eva.miller@example'
```

Como no podemos reconstruir con certeza la dirección correcta en esos casos, los trataremos como valores ausentes. Primero eliminaremos espacios al comienzo y al final con:

```python
.str.strip()
```

Luego volveremos a aplicar el patrón de validación y convertiremos en `pd.NA` aquellos valores que sigan sin cumplirlo.


In [ ]:
df["Email"] = df["Email"].str.strip()

email_valido = df["Email"].str.match(patron_email, na=False)

df.loc[
    df["Email"].notna() & ~email_valido,
    "Email"
] = pd.NA

df["Email"].isna().sum()

np.int64(14)

La columna `Email` quedó con 14 valores ausentes. Los correos que solo tenían espacios al comienzo o al final pudieron conservarse después de la normalización.

En cambio, los valores con errores de estructura quedaron representados como ausentes, ya que no disponemos de información suficiente para reconstruirlos correctamente.


---

## Revisión de `Phone`

La columna `Phone` fue interpretada por Pandas como `int64`, es decir, como un número entero.

Sin embargo, un número de teléfono no representa una cantidad: no tiene sentido calcular su media, sumarlo ni compararlo como si fuera una magnitud numérica.

Además, en las salidas anteriores observamos que los valores aparecen con signo negativo.

Por eso conviene inspeccionar algunos ejemplos antes de decidir cómo transformar esta columna.


In [ ]:
df["Phone"].head(10)

,Phone
0,-1651623197
1,-1898471390
2,-5596363211
3,-3476490784
4,-1586734256
5,-5409003485
6,-4518376063
7,-4134327559
8,-4177656123
9,-8156985699


Los primeros valores aparecen como números enteros negativos:

```text
-1651623197
-1898471390
-5596363211
...
```

Esto confirma dos cosas:

* Pandas almacenó la columna como `int64`;
* los valores contienen un signo negativo que no tiene sentido en un número de teléfono.

Además, aunque estén formados por dígitos, los teléfonos funcionan como identificadores, no como cantidades numéricas.

Por eso conviene convertir esta columna a texto y eliminar el signo negativo.


Primero utilizaremos `.abs()` para obtener el valor absoluto y eliminar el signo negativo.

Luego aplicaremos `.astype("string")` para almacenar los teléfonos como cadenas de texto.


In [ ]:
df["Phone"] = df["Phone"].abs().astype("string")

df["Phone"].head(10)

,Phone
0,1651623197
1,1898471390
2,5596363211
3,3476490784
4,1586734256
5,5409003485
6,4518376063
7,4134327559
8,4177656123
9,8156985699


La columna `Phone` quedó almacenada como `string` y los primeros valores ya no contienen el signo negativo:

```text
1651623197
1898471390
5596363211
...
```

Esto representa mejor la naturaleza de la variable: sigue siendo un dato compuesto por dígitos, pero ya no será tratado como una magnitud numérica.


## Revisión de la estructura después de las transformaciones

Hasta este punto realizamos varias modificaciones:

* eliminamos duplicados completos;
* eliminamos registros con `Employee_ID` conflictivos;
* corregimos valores inválidos en `Age` y `Salary`;
* normalizamos `Status`;
* limpiamos y separamos `Department_Region`;
* normalizamos `Performance_Score`;
* convertimos `Remote_Work` a booleano;
* convertimos `Join_Date` a fecha;
* limpiamos `Email`;
* convertimos `Phone` a texto;
* agregamos las columnas `Department` y `Region`.

Antes de continuar con el tratamiento de valores ausentes, conviene revisar nuevamente la estructura general del DataFrame para comprobar cómo quedaron los tipos de datos y la cantidad de valores no nulos.


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1012 entries, 0 to 1019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   Employee_ID        1012 non-null   object        
 1   First_Name         1012 non-null   object        
 2   Last_Name          1012 non-null   object        
 3   Age                798 non-null    float64       
 4   Department_Region  1004 non-null   object        
 5   Status             1003 non-null   object        
 6   Join_Date          998 non-null    datetime64[ns]
 7   Salary             978 non-null    float64       
 8   Email              998 non-null    object        
 9   Phone              1012 non-null   string        
 10  Performance_Score  1002 non-null   object        
 11  Remote_Work        1007 non-null   boolean       
 12  Department         1004 non-null   object        
 13  Region             1004 non-null   object        
dtypes: boolean(1)

Después de las transformaciones realizadas, el DataFrame contiene:

```text
1012 filas
14 columnas
```

También podemos comprobar que algunos tipos de datos cambiaron respecto de la carga inicial.

Por ejemplo:

```text
Join_Date   → datetime64[ns]
Phone       → string
Remote_Work → boolean
```

Además, se incorporaron las nuevas columnas:

```text
Department
Region
```

Aún quedan valores ausentes en varias variables, entre ellas:

```text
Age
Department_Region
Status
Join_Date
Salary
Email
Performance_Score
Remote_Work
Department
Region
```

Hasta aquí trabajamos paso a paso con distintos tipos de problemas: duplicados, valores extremos, inconsistencias categóricas, errores de escritura, formatos de fecha inválidos y tipos de datos inadecuados.

A partir de este punto, el tratamiento detallado de las columnas restantes puede realizarse siguiendo la misma lógica:

1. inspeccionar los valores;
2. identificar posibles problemas;
3. definir un criterio de limpieza;
4. aplicar la transformación;
5. verificar el resultado.

Este procedimiento es más importante que memorizar una instrucción particular: en un problema real, cada columna puede requerir una estrategia diferente según el significado de los datos.


## Tratamiento de valores ausentes

Hasta ahora identificamos y corregimos distintos problemas de calidad, pero todavía quedan valores ausentes en varias columnas.

Antes de completar o eliminar esos registros conviene recordar una idea importante:

> **No existe una única estrategia correcta para tratar valores faltantes.**

La decisión depende del significado de cada variable, de la cantidad de datos faltantes y del uso que posteriormente haremos del dataset.

En nuestro caso podemos distinguir, por ejemplo:

* variables numéricas, como `Age` y `Salary`;
* variables categóricas, como `Status`, `Department`, `Region` y `Performance_Score`;
* variables especiales, como `Join_Date`, `Email` y `Remote_Work`.

Primero revisaremos nuevamente cuántos valores ausentes quedan en cada columna.


In [ ]:
df.isna().sum()

,0
Employee_ID,0
First_Name,0
Last_Name,0
Age,214
Department_Region,8
Status,9
Join_Date,14
Salary,34
Email,14
Phone,0


## ¿Qué proporción de datos falta en cada columna?

El número absoluto de valores ausentes es útil, pero no siempre alcanza para evaluar su importancia.

Por ejemplo, 20 valores faltantes pueden ser pocos en un dataset de 100.000 registros, pero representar una proporción importante en uno de 100 filas.

Por eso calcularemos también el **porcentaje de valores ausentes** de cada columna.

Para ello:

* `isna().sum()` cuenta los valores faltantes;
* `len(df)` indica la cantidad total de filas;
* multiplicamos por `100` para expresar el resultado como porcentaje;
* `round(2)` limita la visualización a dos decimales.


In [ ]:
faltantes = pd.DataFrame({
    "Cantidad": df.isna().sum(),
    "Porcentaje": (df.isna().sum() / len(df) * 100).round(2)
})

faltantes[faltantes["Cantidad"] > 0]

,Cantidad,Porcentaje
Age,214,21.15
Department_Region,8,0.79
Status,9,0.89
Join_Date,14,1.38
Salary,34,3.36
Email,14,1.38
Performance_Score,10,0.99
Remote_Work,5,0.49
Department,8,0.79
Region,8,0.79


## Estrategias para tratar los valores ausentes

Los porcentajes muestran situaciones diferentes.

La columna `Age` tiene un **21,15 %** de valores ausentes, por lo que eliminar todas esas filas supondría descartar una parte importante del dataset.

En `Salary`, en cambio, los faltantes representan un **3,36 %**, y en las demás variables el porcentaje es todavía menor.

Una alternativa a eliminar registros consiste en **imputar** los valores faltantes: reemplazarlos utilizando algún criterio razonable.

Para variables numéricas son frecuentes estrategias como:

* reemplazar por la **media**;
* reemplazar por la **mediana**;
* utilizar algún valor calculado a partir de otras variables.

La elección no debería hacerse automáticamente. Antes conviene conocer las medidas de tendencia central de nuestras variables numéricas.

Calcularemos la media, la mediana y la moda de `Age` y `Salary` antes de decidir qué utilizar.


In [ ]:
print("Age")
print("Media:  ", df["Age"].mean())
print("Mediana:", df["Age"].median())
print("Moda:   ", df["Age"].mode().tolist())

print("\nSalary")
print("Media:  ", df["Salary"].mean())
print("Mediana:", df["Salary"].median())
print("Moda:   ", df["Salary"].mode().tolist())

Age
Media:   32.5187969924812
Mediana: 30.0
Moda:    [40.0]

Salary
Media:   85221.22244376277
Mediana: 85621.85
Moda:    [51990.98, 52031.74, 52615.44, 60687.63, 62603.98, 63049.22, 67492.73, 69146.95, 71148.27, 71318.79, 77764.24, 77821.79, 82547.26, 90224.82, 100215.06, 114587.11, 115229.12, 116680.63]


## Elección de una estrategia de imputación

Las medidas calculadas muestran situaciones diferentes.

Para `Age` obtuvimos:

```text
Media   = 32.52
Mediana = 30
Moda    = 40
```

La variable solo contiene actualmente las edades `25`, `30`, `35` y `40`.

Si utilizáramos la media para completar los valores faltantes introduciríamos edades como `32.52`, que no aparecen entre los valores observados y que, en este dataset, resultarían poco naturales.

La mediana, en cambio, es:

```text
30
```

y corresponde a uno de los valores existentes en la columna. Por eso utilizaremos la **mediana** para imputar `Age`.

Para `Salary` encontramos:

```text
Media   ≈ 85221.22
Mediana ≈ 85621.85
```

Ambos valores son bastante próximos.

Además, la salida de `mode()` contiene muchos resultados, por lo que no existe una única moda claramente representativa.

Como ya eliminamos los valores extremos detectados y la mediana es una medida robusta frente a posibles valores alejados del centro, utilizaremos también la **mediana** para completar los salarios faltantes.

> La estrategia de imputación elegida forma parte de las decisiones de preparación del dataset y debe quedar documentada.


### Imputación de `Age` y `Salary`

El método `fillna()` permite reemplazar valores ausentes.

Calcularemos la mediana de cada variable y utilizaremos ese valor para completar sus `NaN`.


In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

print("Valores ausentes en Age:", df["Age"].isna().sum())
print("Valores ausentes en Salary:", df["Salary"].isna().sum())

Valores ausentes en Age: 0
Valores ausentes en Salary: 0


## Resultado de la imputación numérica

Después de completar los valores faltantes con la mediana correspondiente:

```text
Age    → 0 valores ausentes
Salary → 0 valores ausentes
```

De esta manera, ambas variables numéricas quedaron completas sin necesidad de eliminar registros adicionales.


## Valores ausentes en variables categóricas

Para las variables categóricas, una estrategia posible consiste en reemplazar los valores ausentes por la categoría más frecuente.

Antes de hacerlo, revisaremos cuál es la moda de cada columna.


In [ ]:
columnas_categoricas = [
    "Status",
    "Department",
    "Region",
    "Performance_Score",
    "Remote_Work"
]

for columna in columnas_categoricas:
    print(columna, "==>", df[columna].mode().tolist())

Status ==> ['Pending']
Department ==> ['DevOps']
Region ==> ['California']
Performance_Score ==> ['Good']
Remote_Work ==> [True]


## Imputación de variables categóricas

En las columnas analizadas obtuvimos una categoría modal clara:

```text
Status            ==> Pending
Department        ==> DevOps
Region            ==> California
Performance_Score ==> Good
Remote_Work       ==> True
```

Como la proporción de valores ausentes en estas variables es pequeña, utilizaremos la **moda** de cada columna para completar los datos faltantes.

Esta es una estrategia sencilla y frecuente para variables categóricas, aunque no debe aplicarse automáticamente en todos los problemas: siempre conviene considerar el significado de la variable y el contexto de los datos.


In [ ]:
columnas_categoricas = [
    "Status",
    "Department",
    "Region",
    "Performance_Score",
    "Remote_Work"
]

for columna in columnas_categoricas:
    df[columna] = df[columna].fillna(df[columna].mode()[0])

df[columnas_categoricas].isna().sum()

,0
Status,0
Department,0
Region,0
Performance_Score,0
Remote_Work,0


Después de completar cada variable categórica con su moda, todas las columnas tratadas quedaron sin valores ausentes. Con esto quedan completas tanto las variables numéricas `Age` y `Salary` como las variables categóricas que acabamos de tratar.


## Feature engineering a partir de `Join_Date`

Una fecha suele contener más información que la cadena original.

A partir de `Join_Date` podemos obtener nuevas variables como:

* el año de ingreso;
* el mes de ingreso.

Estas variables pueden resultar más fáciles de utilizar posteriormente en un modelo que la fecha completa.

Como `Join_Date` ya tiene tipo `datetime64[ns]`, podemos acceder a sus componentes mediante `.dt`.


In [ ]:
df["Join_Year"] = df["Join_Date"].dt.year
df["Join_Month"] = df["Join_Date"].dt.month

df[["Join_Date", "Join_Year", "Join_Month"]].head(10)

,Join_Date,Join_Year,Join_Month
0,2021-04-02,2021.0,4.0
1,2020-07-10,2020.0,7.0
2,2023-12-07,2023.0,12.0
3,2021-11-27,2021.0,11.0
4,2022-01-05,2022.0,1.0
5,2020-06-10,2020.0,6.0
6,2020-04-03,2020.0,4.0
7,2022-07-17,2022.0,7.0
8,2023-12-08,2023.0,12.0
9,2022-08-04,2022.0,8.0


## Resultado de la extracción de año y mes

Las nuevas variables se obtuvieron correctamente a partir de `Join_Date`.

Por ejemplo:

```text
2021-04-02 → año 2021, mes 4
2020-07-10 → año 2020, mes 7
2023-12-07 → año 2023, mes 12
```

Podemos observar que `Join_Year` y `Join_Month` aparecen inicialmente con valores como `2021.0` o `4.0`.

Esto puede ocurrir porque todavía existen fechas ausentes en `Join_Date`. Al propagarse esos faltantes a las nuevas columnas, Pandas necesita representar conjuntamente números y valores ausentes.

Antes de decidir cómo tratar estos casos, comprobaremos cuántos valores faltantes quedaron en las tres variables.


In [ ]:
df[["Join_Date", "Join_Year", "Join_Month"]].isna().sum()

,0
Join_Date,14
Join_Year,14
Join_Month,14


## Tratamiento de fechas de ingreso ausentes

Los 14 valores ausentes de `Join_Date` también aparecen, como era esperable, en las nuevas variables:

```text
Join_Year  ==> 14
Join_Month ==> 14
```

En este caso no contamos con información suficiente para reconstruir la fecha de ingreso de esos empleados.

Podríamos imputar un año o un mes utilizando algún valor frecuente, pero eso introduciría información inventada en una variable temporal.

Como la cantidad de registros afectados es pequeña en relación con el total del dataset, optaremos por eliminar esas filas.


### Eliminación de filas con `Join_Date` ausente

Utilizaremos `dropna()` indicando específicamente la columna `Join_Date`.

De esta manera se eliminarán únicamente las filas en las que falte esa fecha, sin afectar otros registros.


In [ ]:
df = df.dropna(subset=["Join_Date"])

df.shape

(998, 16)

## Resultado del tratamiento de `Join_Date`

Después de eliminar las filas con fecha de ingreso ausente, el DataFrame quedó con:

```text
998 filas
16 columnas
```

Las 14 filas eliminadas corresponden exactamente a los registros que no tenían una fecha de ingreso válida.

Además, el número de columnas aumentó respecto del dataset original porque incorporamos nuevas variables derivadas:

```text
Department
Region
Join_Year
Join_Month
```

A partir de este punto ya no tenemos valores ausentes asociados a `Join_Date`, `Join_Year` ni `Join_Month`.


## Selección de variables

No todas las columnas de un dataset resultan necesariamente útiles para un modelo de Machine Learning.

En nuestro caso hay algunas variables que ya cumplieron su función o que actúan principalmente como identificadores:

```text
Employee_ID
First_Name
Last_Name
Email
Phone
Department_Region
Join_Date
```

`Department_Region` ya fue descompuesta en `Department` y `Region`.

De manera similar, `Join_Date` dio origen a `Join_Year` y `Join_Month`.

Las columnas `Employee_ID`, `First_Name`, `Last_Name`, `Email` y `Phone` identifican o describen individualmente a cada empleado, pero no representan características que necesariamente queramos utilizar para construir un modelo.

Por eso crearemos una nueva versión del DataFrame eliminando estas columnas.

Conservaremos `df` como referencia y utilizaremos un nuevo DataFrame llamado `df_ml` para continuar con la preparación orientada a Machine Learning.

### Eliminación de columnas

El método `drop()` permite eliminar filas o columnas.

En este caso utilizaremos:

```python
columns=[...]
```

para indicar explícitamente qué columnas queremos quitar.


In [ ]:
columnas_a_eliminar = [
    "Employee_ID",
    "First_Name",
    "Last_Name",
    "Email",
    "Phone",
    "Department_Region",
    "Join_Date"
]

df_ml = df.drop(columns=columnas_a_eliminar)

df_ml.head()

,Age,Status,Salary,Performance_Score,Remote_Work,Department,Region,Join_Year,Join_Month
0,25.0,Active,59767.65,Average,True,DevOps,California,2021.0,4.0
1,30.0,Active,65304.66,Excellent,True,Finance,Texas,2020.0,7.0
2,30.0,Pending,88145.90,Good,True,Admin,Nevada,2023.0,12.0
3,25.0,Inactive,69450.99,Good,True,Admin,Nevada,2021.0,11.0
4,25.0,Active,109324.61,Poor,False,Cloud Tech,Florida,2022.0,1.0


El nuevo DataFrame `df_ml` conserva las variables que consideramos potencialmente útiles para una etapa posterior de Machine Learning:

```text
Age
Status
Salary
Performance_Score
Remote_Work
Department
Region
Join_Year
Join_Month
```

Las columnas utilizadas principalmente como identificadores, datos personales o información redundante quedaron fuera de esta nueva versión.

A partir de este punto trabajaremos sobre `df_ml`.

Todavía quedan variables categóricas representadas como texto, por ejemplo:

```text
Status
Performance_Score
Department
Region
```

Los algoritmos de Machine Learning generalmente necesitan trabajar con valores numéricos, por lo que el siguiente paso será estudiar cómo transformar estas categorías sin perder su significado.


### Revisión de los tipos de datos de `df_ml`

Antes de transformar las variables categóricas, comprobaremos qué tipo de dato tiene actualmente cada columna.


In [ ]:
df_ml.dtypes

,0
Age,float64
Status,object
Salary,float64
Performance_Score,object
Remote_Work,boolean
Department,object
Region,object
Join_Year,float64
Join_Month,float64


La revisión de `df_ml.dtypes` muestra que las variables categóricas que todavía necesitan transformación son:

```text
Status
Performance_Score
Department
Region
```

`Remote_Work`, en cambio, ya está representada como una variable booleana.

También observamos que:

```text
Join_Year
Join_Month
```

continúan almacenadas como `float64`.

Esto se debía a que originalmente podían contener valores ausentes. Como esos registros ya fueron eliminados, podemos representar ahora ambas variables mediante números enteros.


In [ ]:
df_ml["Join_Year"] = df_ml["Join_Year"].astype("int64")
df_ml["Join_Month"] = df_ml["Join_Month"].astype("int64")

df_ml[["Join_Year", "Join_Month"]].dtypes

,0
Join_Year,int64
Join_Month,int64


## Variables categóricas: nominales y ordinales

No todas las variables categóricas tienen la misma naturaleza.

En `df_ml` encontramos, por ejemplo:

```text
Status
Department
Region
Performance_Score
```

Las variables `Status`, `Department` y `Region` son **nominales**: sus categorías representan grupos diferentes, pero no existe un orden natural entre ellas.

Por ejemplo:

```text
California
Florida
Texas
```

son simplemente categorías distintas.

En cambio, `Performance_Score` es una variable **ordinal**, porque sus categorías sí poseen un orden:

```text
Poor < Average < Good < Excellent
```

Esta diferencia es importante porque no conviene codificar ambos tipos de variables de la misma manera.

Para las variables nominales utilizaremos más adelante una codificación que no introduzca un orden artificial.

Para `Performance_Score`, en cambio, podemos asignar valores numéricos respetando su jerarquía.


### Codificación ordinal de `Performance_Score`

Asignaremos los siguientes valores:

```text
Poor      ==> 0
Average   ==> 1
Good      ==> 2
Excellent ==> 3
```

De esta forma, los números conservan el orden conceptual de las categorías.


In [ ]:
orden_performance = {
    "Poor": 0,
    "Average": 1,
    "Good": 2,
    "Excellent": 3
}

df_ml["Performance_Score"] = df_ml["Performance_Score"].map(orden_performance)

df_ml["Performance_Score"].value_counts().sort_index()

,count
Performance_Score,
0,204
1,261
2,274
3,259


La variable `Performance_Score` quedó transformada y la variable conserva el orden natural de las categorías y ya puede ser utilizada como una característica numérica.


## Codificación de variables nominales con scikit-learn

Las variables:

```text
Status
Department
Region
```

son categóricas nominales, es decir, sus categorías no tienen un orden natural.

Para transformarlas utilizaremos `OneHotEncoder` de **scikit-learn**.

Este transformador crea una nueva columna binaria por cada categoría encontrada.

Por ejemplo, una variable como:

```text
Status
```

puede convertirse en columnas como:

```text
Status_Active
Status_Inactive
Status_Pending
```

En cada fila, una de esas columnas tendrá valor `1` y las demás `0`, según la categoría correspondiente.

A diferencia de `pd.get_dummies()`, `OneHotEncoder` forma parte del ecosistema de scikit-learn y más adelante podremos incorporarlo directamente dentro de un `Pipeline`.

### Configuración de `OneHotEncoder`

Utilizaremos:

```python
handle_unknown="ignore"
```

para evitar errores si en el futuro aparecen categorías que no estaban presentes durante el ajuste del codificador.

También indicaremos:

```python
sparse_output=False
```

para obtener una matriz densa, más cómoda de visualizar en este cuaderno.

Primero ajustaremos el codificador a las columnas categóricas y luego observaremos qué nombres tendrán las nuevas variables.


In [ ]:
from sklearn.preprocessing import OneHotEncoder

columnas_nominales = [
    "Status",
    "Department",
    "Region"
]

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

encoder.fit(df_ml[columnas_nominales])

encoder.get_feature_names_out(columnas_nominales)

array(['Status_Active', 'Status_Inactive', 'Status_Pending',
       'Department_Admin', 'Department_Cloud Tech', 'Department_DevOps',
       'Department_Finance', 'Department_HR', 'Department_Sales',
       'Region_California', 'Region_Florida', 'Region_Illinois',
       'Region_Nevada', 'Region_New York', 'Region_Texas'], dtype=object)

## Variables generadas por `OneHotEncoder`

El codificador detectó las categorías presentes en `Status`, `Department` y `Region`, y preparó las siguientes variables:

```text
Status_Active
Status_Inactive
Status_Pending

Department_Admin
Department_Cloud Tech
Department_DevOps
Department_Finance
Department_HR
Department_Sales

Region_California
Region_Florida
Region_Illinois
Region_Nevada
Region_New York
Region_Texas
```

Cada una representará una categoría mediante valores binarios.

Por ejemplo, para un empleado cuyo estado sea `Active`:

```text
Status_Active   = 1
Status_Inactive = 0
Status_Pending  = 0
```

Ahora que conocemos las columnas que se crearán, podemos realizar la transformación y convertir el resultado nuevamente en un DataFrame de Pandas.

### Aplicación de la codificación

El método:

```python
encoder.transform(...)
```

aplica la transformación aprendida por `OneHotEncoder`.

El resultado es una matriz de NumPy, por lo que la convertiremos a un DataFrame utilizando los nombres obtenidos con `get_feature_names_out()`.

Finalmente eliminaremos las tres columnas categóricas originales y agregaremos las nuevas columnas codificadas.


In [ ]:
datos_codificados = encoder.transform(df_ml[columnas_nominales])

df_codificado = pd.DataFrame(
    datos_codificados,
    columns=encoder.get_feature_names_out(columnas_nominales),
    index=df_ml.index
)

df_ml = pd.concat(
    [
        df_ml.drop(columns=columnas_nominales),
        df_codificado
    ],
    axis=1
)

df_ml.head()

,Age,Salary,Performance_Score,Remote_Work,Join_Year,Join_Month,Status_Active,Status_Inactive,Status_Pending,Department_Admin,...,Department_DevOps,Department_Finance,Department_HR,Department_Sales,Region_California,Region_Florida,Region_Illinois,Region_Nevada,Region_New York,Region_Texas
0,25.0,59767.65,1,True,2021,4,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,30.0,65304.66,3,True,2020,7,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,30.0,88145.90,2,True,2023,12,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,25.0,69450.99,2,True,2021,11,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,25.0,109324.61,0,False,2022,1,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0


Después de aplicar `OneHotEncoder`, las columnas categóricas nominales originales fueron reemplazadas por variables binarias.

Por ejemplo, `Status` dejó de aparecer como una única columna de texto y fue reemplazada por:

```text
Status_Active
Status_Inactive
Status_Pending
```

Lo mismo ocurrió con `Department` y `Region`.

Cada nueva columna toma valores `0` o `1` según corresponda a la categoría de cada registro.

El DataFrame `df_ml` quedó ahora con **21 columnas**.

En esta etapa ya no tenemos variables nominales representadas como texto.


## Comprobación final del dataset preparado

Antes de dar por terminada la preparación del dataset conviene realizar una última revisión.

Vamos a comprobar:

* las dimensiones finales;
* los tipos de datos;
* la cantidad total de valores ausentes;
* si quedan filas duplicadas.

Todavía no dividiremos los datos en entrenamiento y prueba ni entrenaremos modelos. El objetivo de este cuaderno termina en dejar el conjunto de datos preparado para esa etapa posterior.


In [ ]:
print("Dimensiones:", df_ml.shape)
print("\nValores ausentes totales:", df_ml.isna().sum().sum())
print("Filas duplicadas:", df_ml.duplicated().sum())

print("\nTipos de datos:")
print(df_ml.dtypes)

Dimensiones: (998, 21)

Valores ausentes totales: 0
Filas duplicadas: 2

Tipos de datos:
Age                      float64
Salary                   float64
Performance_Score          int64
Remote_Work              boolean
Join_Year                  int64
Join_Month                 int64
Status_Active            float64
Status_Inactive          float64
Status_Pending           float64
Department_Admin         float64
Department_Cloud Tech    float64
Department_DevOps        float64
Department_Finance       float64
Department_HR            float64
Department_Sales         float64
Region_California        float64
Region_Florida           float64
Region_Illinois          float64
Region_Nevada            float64
Region_New York          float64
Region_Texas             float64
dtype: object


## Auditoría final: aparecen nuevamente filas duplicadas

La revisión final muestra:

```text
Dimensiones: 998 filas × 21 columnas
Valores ausentes: 0
Filas duplicadas: 2
```

El dataset ya no contiene valores ausentes y todas sus variables están representadas mediante tipos utilizables en una etapa posterior de Machine Learning.

Sin embargo, aparecen **2 filas duplicadas** en `df_ml`.

Esto no implica necesariamente que hayan reaparecido los duplicados originales.

Recordemos que para construir `df_ml` eliminamos columnas como:

```text
Employee_ID
First_Name
Last_Name
Email
Phone
```

Por lo tanto, dos empleados diferentes podrían tener ahora exactamente los mismos valores en todas las características que conservamos.

Antes de decidir si estas filas deben eliminarse, conviene inspeccionarlas y compararlas con los registros correspondientes del DataFrame original ya limpio.


### Inspección de los duplicados después de la selección de variables

Utilizaremos nuevamente:

```python
duplicated(keep=False)
```

para localizar todas las filas de `df_ml` que forman parte de algún grupo repetido.

Conservaremos sus índices y los utilizaremos para consultar en `df` algunos datos identificatorios, especialmente `Employee_ID`.

Así podremos comprobar si se trata realmente del mismo empleado repetido o de empleados diferentes que simplemente poseen las mismas características en `df_ml`.


In [ ]:
indices_duplicados_ml = df_ml[
    df_ml.duplicated(keep=False)
].index

df.loc[
    indices_duplicados_ml,
    [
        "Employee_ID",
        "First_Name",
        "Last_Name",
        "Age",
        "Salary",
        "Status",
        "Performance_Score",
        "Remote_Work",
        "Department",
        "Region",
        "Join_Year",
        "Join_Month"
    ]
].sort_index()

,Employee_ID,First_Name,Last_Name,Age,Salary,Status,Performance_Score,Remote_Work,Department,Region,Join_Year,Join_Month
411,EMP1411,Grace,Garcia,25.0,60687.63,Pending,Excellent,False,DevOps,Illinois,2023.0,6.0
626,EMP1626,Grace,Jones,30.0,77821.79,Inactive,Average,False,HR,Illinois,2023.0,10.0
1004,EMP2004,Carol,Smith,25.0,60687.63,Pending,Excellent,False,DevOps,Illinois,2023.0,6.0
1006,EMP2006,Grace,Brown,30.0,77821.79,Inactive,Average,False,HR,Illinois,2023.0,10.0


## ¿Son realmente registros duplicados?

Al recuperar la información identificatoria de las filas involucradas, observamos dos pares de empleados:

```text
EMP1411 y EMP2004
EMP1626 y EMP2006
```

Los `Employee_ID` son diferentes y también aparecen diferencias en los nombres.

Sin embargo, dentro de cada par coinciden todas las variables que conservamos para construir `df_ml`.

Por ejemplo, `EMP1411` y `EMP2004` comparten:

```text
Age               = 25
Salary            = 60687.63
Status            = Pending
Performance_Score = Excellent
Remote_Work       = False
Department        = DevOps
Region            = Illinois
Join_Year         = 2023
Join_Month        = 6
```

Por eso, una vez eliminadas las columnas identificatorias, ambas observaciones se convierten en filas idénticas dentro de `df_ml`.

Pero **no representan el mismo registro**: corresponden a empleados diferentes.

Este caso muestra que:

> Una fila duplicada en el conjunto de características no necesariamente representa un registro duplicado en los datos originales.

Por lo tanto, **conservaremos estas filas**.

El criterio utilizado al comienzo del proceso sigue siendo válido: eliminamos registros cuando comprobamos que eran copias del mismo empleado, pero no eliminaremos empleados diferentes solamente porque compartan las mismas características.

## Estado final del dataset

Antes de finalizar, realizaremos una última revisión de `df_ml`.

En este punto sabemos que las dos filas que Pandas identifica como duplicadas **no constituyen errores de duplicación**, sino empleados diferentes que comparten las mismas características.

Por lo tanto, no las eliminaremos.


In [ ]:
print("Dimensiones finales:", df_ml.shape)
print("Valores ausentes:", df_ml.isna().sum().sum())
print("Filas con características repetidas:", df_ml.duplicated().sum())

print("\nTipos de datos:")
print(df_ml.dtypes)

Dimensiones finales: (998, 21)
Valores ausentes: 0
Filas con características repetidas: 2

Tipos de datos:
Age                      float64
Salary                   float64
Performance_Score          int64
Remote_Work              boolean
Join_Year                  int64
Join_Month                 int64
Status_Active            float64
Status_Inactive          float64
Status_Pending           float64
Department_Admin         float64
Department_Cloud Tech    float64
Department_DevOps        float64
Department_Finance       float64
Department_HR            float64
Department_Sales         float64
Region_California        float64
Region_Florida           float64
Region_Illinois          float64
Region_Nevada            float64
Region_New York          float64
Region_Texas             float64
dtype: object


## Resultado final de la preparación del dataset

Después de completar todas las etapas de exploración, limpieza y transformación, `df_ml` quedó con:

```text
998 filas
21 columnas
```

Además:

```text
Valores ausentes: 0
```

y las variables quedaron representadas mediante tipos numéricos o booleanos adecuados para una etapa posterior de Machine Learning.

También aparecen:

```text
2 filas con características repetidas
```

pero ya comprobamos que corresponden a empleados diferentes cuyos valores coinciden en todas las variables conservadas en `df_ml`. Por lo tanto, no se consideran registros duplicados y se mantienen en el dataset.

A lo largo del proceso realizamos, entre otras tareas:

* inspección inicial del dataset;
* detección y eliminación de duplicados reales;
* revisión de identificadores repetidos;
* detección y tratamiento de valores extremos;
* normalización de variables categóricas;
* corrección de errores de texto;
* conversión y validación de fechas;
* tratamiento de valores ausentes;
* separación y creación de nuevas características;
* selección de variables;
* codificación ordinal;
* One-Hot Encoding con scikit-learn;
* revisión final de la estructura del conjunto de datos.

El resultado es un dataset preparado para continuar con las siguientes etapas de un proyecto de Machine Learning.

En este cuaderno no realizamos todavía la división entre datos de entrenamiento y prueba ni entrenamos ningún modelo. Esas tareas pertenecen a la siguiente etapa del proceso.

Una idea fundamental que conviene conservar es:

> **Preparar los datos no consiste solamente en ejecutar funciones de limpieza. Requiere inspeccionar, interpretar, tomar decisiones y verificar cada transformación realizada.**


## Guardado del dataset preparado

Una vez finalizada la preparación podemos guardar `df_ml` en un nuevo archivo CSV.

Utilizaremos:

```python
to_csv()
```

El argumento:

```python
index=False
```

evita guardar el índice interno de Pandas como una columna adicional.

De esta manera podremos utilizar el dataset preparado en otro cuaderno o en una etapa posterior del curso sin tener que repetir todo el proceso de limpieza.


In [ ]:
df_ml.to_csv("Employee_dataset_preparado.csv", index=False)

print("Dataset guardado correctamente.")

Dataset guardado correctamente.


## Actividad de cierre

Antes de continuar con las siguientes etapas de Machine Learning, intentá responder brevemente las siguientes preguntas.

1. ¿Por qué no era suficiente utilizar solamente `df.drop_duplicates()` para detectar todos los problemas de duplicación del dataset?

2. Al finalizar aparecieron dos filas idénticas en `df_ml`. ¿Por qué decidimos conservarlas?

3. ¿Por qué los valores extremos de `Age` y `Salary` no fueron tratados exactamente de la misma manera desde el comienzo?

4. ¿Qué diferencia existe entre una variable categórica **nominal** y una **ordinal**?

5. ¿Por qué utilizamos una codificación ordinal para `Performance_Score`, pero `OneHotEncoder` para `Status`, `Department` y `Region`?

6. ¿Por qué convertimos `Phone` a texto aunque estuviera formado únicamente por números?

7. ¿Qué ventaja tuvo transformar `Join_Date` en un tipo `datetime` antes de crear `Join_Year` y `Join_Month`?

8. ¿Por qué evitamos inventar valores para las fechas de ingreso que no podían recuperarse?

9. ¿Qué diferencia existe entre **detectar un problema** en los datos y **decidir cómo corregirlo**?

10. Al finalizar este cuaderno, ¿qué tareas importantes del proceso de Machine Learning todavía no realizamos?

Estas preguntas no buscan solamente recordar instrucciones de Pandas o scikit-learn. El objetivo es poder justificar las decisiones tomadas durante la preparación de los datos.
